spec:
  name: node-webhook-worker
  rolloutGroup: worker
  autoSync: true
  destination:
    namespace: unique
  source:
    # HPE: oci://harbor.ingress.pcai0201.fr2.hpecolo.net/unique/helm/webhook-worker
    repoURL: oci://harbor.localhost/unique/helm/webhook-worker
    targetRevision: sha256:14c6c95f11ec607cb1f83625c0eb30677ff9b9b65423e8d3fb649244a0615360
    path: .
    helm:
      passCredentials: true
      releaseName: node-webhook-worker
      valuesObject:
        global:
          image:
            # HPE: harbor.ingress.pcai0201.fr2.hpecolo.net
            registry: harbor.localhost
            pullSecrets:
              - name: harbor-pull-secret
        env:
          UNIQUE_INSTALLATION_ID: hpe-hosted-trial
          # HPE: https://id.ingress.pcai0201.fr2.hpecolo.net
          ZITADEL_ISSUER: http://id.localhost
          ZITADEL_PROJECT_ID: hpe-hosted-trial
        routes:
          gateway:
            name: unique
            namespace: unique
          # HPE: api.ingress.pcai0201.fr2.hpecolo.net
          hostname: api.localhost
        internalServices:
          namespace: unique
        postgresql:
          connection:
            host: postgres-rw.unique.svc.cluster.local
            port: 5432
        redis:
          connection:
            host: redis-master.unique.svc.cluster.local
            port: 6379
        rabbitmq:
          connection:
            host: rabbitmq.unique.svc.cluster.local
            url:
              fromSecret:
                name: node-webhook-worker-connections
                key: AMQP_URL
        objectStorage:
          endpoint: http://rustfs-svc.unique.svc.cluster.local:9000
          region: us-east-1
        litellm:
          enabled: true
          connection:
            host: litellm.unique.svc.cluster.local
            port: 4000
        namespaceOverride: unique
