spec:
  name: node-webhook-worker
  rolloutGroup: worker
  autoSync: true
  destination:
    namespace: unique
  source:
    # HPE: oci://harbor.ingress.pcai0201.fr2.hpecolo.net/unique/helm/webhook-worker
    repoURL: oci://harbor.unique.svc.cluster.local/library/helm/webhook-worker
    targetRevision: sha256:14c6c95f11ec607cb1f83625c0eb30677ff9b9b65423e8d3fb649244a0615360
    path: .
    helm:
      passCredentials: true
      releaseName: node-webhook-worker
      valuesObject:
        global:
          image:
            # HPE: harbor.ingress.pcai0201.fr2.hpecolo.net
            registry: harbor.2.28.18.215.sslip.io
            pullSecrets:
              - name: harbor-pull-secret
        image:
          repository: library/images/webhook-worker
          useDigest: false
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/postgres/ca.crt
          MAX_HEAP_MB: 200
          UNIQUE_INSTALLATION_ID: hpe-hosted-trial
          # HPE: https://id.ingress.pcai0201.fr2.hpecolo.net
          ZITADEL_ISSUER: https://id.2.28.18.215.sslip.io
          ZITADEL_PROJECT_ID: hpe-hosted-trial
        volumes:
          - name: postgres-ca
            secret:
              secretName: postgres-ca
              items:
                - key: ca.crt
                  path: ca.crt
        volumeMounts:
          - name: postgres-ca
            mountPath: /etc/ssl/postgres/ca.crt
            subPath: ca.crt
            readOnly: true
        routes:
          gateway:
            name: unique
            namespace: unique
          # HPE: api.ingress.pcai0201.fr2.hpecolo.net
          hostname: api.2.28.18.215.sslip.io
        postgresql:
          connection:
            host: postgres-rw.unique.svc.cluster.local
            port: 5432
        redis:
          connection:
            host: redis-master.unique.svc.cluster.local
            port: 6379
        rabbitmq:
          connection:
            host: rabbitmq.unique.svc.cluster.local
            url:
              fromSecret:
                name: node-webhook-worker-connections
                key: AMQP_URL
        objectStorage:
          endpoint: http://rustfs-svc.unique.svc.cluster.local:9000
          region: us-east-1
        litellm:
          enabled: true
          connection:
            host: litellm.unique.svc.cluster.local
            port: 4000
        namespaceOverride: unique
