---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-webhook-worker-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgC9fXRjbEp3uxyXdl2xDnpqP2roudjDNlw4YyQjAnyIjX0hu3qbv1US7FH3rvCBQLShtP4+4FAfQ4AHKvmc0NJB3pTHhimqjT08cQTQdsNvpAfTZ3PFXDvwGr4FAR+z71Es3/Ajpwog1YXSdM/w/QSO1IjKobZQ9f6XZby0nYzSUrW/Y21cbSvyeYs28RRFwDbsz6TOusuGM3iryPTh4c4DJpZBJdPy8shDid9kuQVUmdokLbp4Abui7koyLJusbXw3Ppf0nPp3Gn/rlzbTDZGERsmhf7IDKfzXUTompsNuMhJKYBt6jh5vZEw0ZZ6GarxWXWXObq/nHss60OHxoNrw4dnLN3tVqqYPePBhh3LFL4MCDtSqK9x2zY5C/4USPzSqRjKk95dNZTdDgupxn1foBcFRFa4YFX1w5IkfVvWqHtn6sWTvuibJZ066fqhNhi276i08G3q0UF5+Ql29rVEYMTmH9qrVMqynhqESOc2LehbKw+O1wl9AJt/otydooWFzeaslgdrJA/BWffEhEVAoGG+by79tkcKYUy3IHHaZ65FsdB4wiya4rYL3+sY7uURtW+CWC0ukqMOHDqeyn0WPkJKES0VyOLhTbpHmYV3WDk7MaajACjyLtZzZTWvUxavdYrjPQk4D58Hcjytj5FH9o8TBdUUF1lWPL43FsNRrWH1UK0zEmE+6tUWvKOu3jyk=
  template:
    metadata:
      name: node-webhook-worker-secrets
      namespace: unique
    type: Opaque
