---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-webhook-worker-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgCzZ0PqvrkV4LtTFzRTZBe1gfC23oC5cM/EElFRHYdQwSoeNnZqe18LRfOLaoI4NX8AJOUXHPs6jIwMiUc/IjNCISiAnqmSiXfVLiZwOMqKNBowtjiUPgPS06Nc2s8CULmQtLMTVYWrFpHFiDpWiAAwbxExHCt6ozXBzn1BSfzO1SfkSt1TjAL24SsbadSnk0MieT/UXoKSgsu2YCILjCsS8kF7J/WTkuO3zyWvrJhVcFqJsJK/0pP/bnn+WiHyFFuX4uehobP8Zzg9BwUqDNtBdE0aQW3mS8TS9vgy+zjP7eOsqM1TjypWD0WfwDl2GGOgKs3Crlz/Q5qVU8zZkBj6dwzN3ZXangOsUXZJ1fcZwmNI6GzNU0uUvN4CWZpTCnQta19njzNVeXHpUj4/cDNWIABijFMTU0+EAXO3rwt5pdlZlwilb/lYf1xYXmncIg3Ddmu1ejiX7OtneXk3Se4ocl9Xt6v+lYB5/z1/he+0St4tLXh89JGgGwEmZ/WMncqdEWIIcW5+PHUOnLaLddVeNcZsyz7MPSdAHZ5ht7lufW0bShZ9vIEjwbcuTgrvU/0vs3wzFrLFUMfD8kyevmYEO9Jrw24+uayaW5uG9xnEBe0aWG910PyE1xjvGLjh61VL8su8a3mssDWOa+Mz1NjnG6JOPEcbEN/X+oirsh4O1SP1iG/ZHC17aIhn/GykYWM=
  template:
    metadata:
      name: node-webhook-worker-secrets
      namespace: unique
    type: Opaque
