{{- if .Values.hooks.migration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-service.fullname" . }}-migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: hooks-db-migration
data:
  VERSION: {{ .Values.image.tag | quote }}
  PORT: {{ include "backend-service.applicationPort" $ | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}