spec:
  name: cert-manager
  metadata:
    argocd.argoproj.io/sync-wave: "1"
  autoSync: false
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.21.1
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        cainjector:
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
        webhook:
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
