---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-scope-management-secrets
  namespace: unique
spec:
  encryptedData:
    ZITADEL_PAT: AgBqJfHmECiHvNIa/ThF1GGWzk6wDkEzGfg04j6q8ib0MeTayI98v5w3hNGmg0GJkyvzBwdD6tRMeA/Y7Z077EY6xe1fNsC3rwfJT7iO516kMttatRCa2I/HovAHkfDoKiAaCrqOJ4njDZHgk3j9LUQeIDtTPV2woecVbvJigSK+ZK4FUuJQRYtg7zRGHo8mU4l9KMIDn7ZATC4FYl8MX450qpbmkVFiXR3QYyniYH/O16g8YYajaQgUJy4UuJXkec9MzLOKf7s8OEaYuN8VnxQ5VrvXWnfCu7m1udn8es7qmuxlWyTY2qT4CLRZTfoC3C6mMBEhL4yWyZjFiZbsrY3Nghfi37RJpaBiBN/6kM2wZGol0+DBPPjGQWDql9ko/lm5yr4N3XRi+9NGU3N3rLAN5dIORBLU4Tk+M56Rf81AnGhDtWCpU/PBZaAscU1VvVrryVXKJ9WKIzI1pCZxfklfG+DoKgtSQwZaFmpqNqHNKzoNl2wWcWJovDyO3RCQwLc+PwVL/CUfVxaw2nGWYWN0uoo99lku/uHoPPJI7IuwNFKZlGz2rjcEa8jUpcDkMNROw2GuL5yd6PK8prxhSYpVVw6LnP8SuPX/I8F5qnaHQwYkB22i90IJpLkXqkIOWEIPXsvjoSPB3TsSBzrlg+T+Jm+Z5CYE4LzfV5FdmYV1/UJrCpqASu0pJMFf34XZjDg=
  template:
    metadata:
      name: node-scope-management-secrets
      namespace: unique
    type: Opaque
