---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-scope-management-secrets
  namespace: unique
spec:
  encryptedData:
    ZITADEL_PAT: AgCXtMvQIvGADJsrxgqvkA8zO9aFP9F7KHIOIW/fn5ARtubV22r5JubGfz2WsI2vvtzl8rMieJtBkGWmGarsCJhrobtK0tq+QlWtICQpBnONxSDYKIZybFgJBJ2NM2lnzB0bJ2MSe6n8a3Jp4I3rmfn9up9625WZeuZ9gKxi3mCKXi2/j3zh3L6bEzTPKsyqbd7eb4GcwDIBAE4JMPeuxZxxZ2zeD+qnXOwMgN+xzPkwVQ9ur9MmDRBIJF7Ugouqp5yY/kkfigDc2i7JTQ0SwGwaL0ByodJz2cS131uz0wVLGIHFmB8WlFgwyKdO0CFX7IJ6psmBpSfxKSGw2kyeh2EOYLcsipSgIWjK/QWxE6efyvG/cVGv5pQeb29lgIqjbqFUmD9ZZ9s4IXHQ+pzfLbgZ44W3FuAnLthSu9dL/6X1c1izz9xla72zzZi+AEKi1KEC8n87qs+CcroS3aQjPiyfaF04DfNI9716Q+GP8OCi5yZJS7nZIsOZxHXsyP/zoozGWNSeyAr/ufxsVsVNVqetLqnjZ/KTnSmsp0wtJdA1IN6CEwIRnsQ8tJ75rBfkijqjeXPMgaUrxZxD2fDhPNfB9aq5kFvFn747s4MCow5mshaMXzP0TKTfgwWSZHDqxt64DjsbnZlSiDhrDg4LTo7tbDoC/zQ9+BViK226xwn7zIMLxv+8lR4M1R+QQ0h3uoo=
  template:
    metadata:
      name: node-scope-management-secrets
      namespace: unique
    type: Opaque
