apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kong-unique-virtual-service
spec:
  gateways:
    - istio-system/ezaf-gateway
  hosts:
    # HPE: unique.ingress.pcai0201.fr2.hpecolo.net
    - unique.localhost
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: kong-gateway-proxy.unique.svc.cluster.local
            port:
              number: 80
