apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: unique-block-route
  annotations:
    kubernetes.io/ingress.class: kong
plugin: request-termination
config:
  status_code: 403
  message: This route is blocked.
