spec:
  name: agentic-ingestion
  rolloutGroup: core
  autoSync: true
  destination:
    namespace: unique
  source:
    # HPE: oci://harbor.ingress.pcai0201.fr2.hpecolo.net/unique/helm/agentic-ingestion
    repoURL: oci://harbor.unique.svc.cluster.local/library/helm/agentic-ingestion
    targetRevision: sha256:8ede2b15c5d7a7c41b6f661874c5ce35a220fc85f8534e78170a844369cb381a
    path: .
    helm:
      passCredentials: true
      releaseName: agentic-ingestion
      valuesObject:
        global:
          image:
            # HPE: harbor.ingress.pcai0201.fr2.hpecolo.net
            registry: harbor.2.28.18.215.sslip.io
            pullSecrets:
              - name: harbor-pull-secret
        image:
          repository: library/images/agentic-ingestion
          useDigest: false
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/postgres/ca.crt
          UNIQUE_INSTALLATION_ID: 388734592988807375
          # HPE: https://id.ingress.pcai0201.fr2.hpecolo.net
          ZITADEL_ISSUER: https://id.2.28.18.215.sslip.io
          ZITADEL_PROJECT_ID: 388734592988807375
        volumes:
          - name: postgres-ca
            secret:
              secretName: postgres-ca
              items:
                - key: ca.crt
                  path: ca.crt
        volumeMounts:
          - name: postgres-ca
            mountPath: /etc/ssl/postgres/ca.crt
            subPath: ca.crt
            readOnly: true
        routes:
          gateway:
            name: unique
            namespace: unique
          # HPE: api.ingress.pcai0201.fr2.hpecolo.net
          hostname: api.2.28.18.215.sslip.io
        postgresql:
          connection:
            host: postgres-rw.unique.svc.cluster.local
            port: 5432
        redis:
          connection:
            host: redis-master.unique.svc.cluster.local
            port: 6379
        rabbitmq:
          connection:
            host: rabbitmq.unique.svc.cluster.local
        objectStorage:
          endpoint: http://rustfs-svc.unique.svc.cluster.local:9000
          region: us-east-1
        litellm:
          enabled: true
          connection:
            host: litellm.unique.svc.cluster.local
            port: 4000
        namespaceOverride: unique
