---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sbx-templates-unique-polyagent-001-secrets
  namespace: unique
spec:
  encryptedData:
    UNIQUE_API_KEY: AgBH4S6bt0GiG0iujpj6yc4YawYCfnr5B8A5C+cSERktE7LHbZapoBdAUgc7FrP/2my7PTHBWVTLzYsKxtRQUA5682se0PYgyn500JUSEvVfiFXVOkQTm4T1ZADBHDgR0wEKTbeEgbemHNPqVPEEUOLVzCwPyfmEHj7+YbutFdoViZr6tl2NLAoCIcZlBd0AtrapU2dHA+Nh7qqBU+8RijQqdf1iIhgByq5eUt69puuAMkGGh2Tr804Hf57qbSCkJPGaARsMTNaWxfak41bhBL2vkDYnZHizCF5+DyPI0Z6Alkb8/M3U+Xtn1uI571L3HTl6/8lMGV3BJPi14ryFCEMgXsaMOZxQgLVkRFjMUbw80MSKMHMGoJ/9JQluIUnkjFLfWTWNHGShQ0Xr6fX+SJjr8jXqXqEA50jBFQJ2VhydrTiW8zzs4NrpNBfNhNPyW3UqSXQS23t0XIK109AVuY2ylL9Mi0mWq6ffrkZbMJmH98DZBEQRDWSeswL+C8yeVwD9lE9SFqQ2bpm9gpJe9mKl2nLtizGkY/TKOVckEz4pXTL7EP2Ql3lrWPuiVzGggU0XPZyIM7nUdWuuXt81N16IToBcoWHEuO/H/v1/dWtxwbZnzO/kf3LPMB3xxgfR6sXWLWxJGNZTznNpsVXx1JfuiWGCE1AnzTK9kxn3i1XJ9AHHRE6oFubxf3qpLyoT1sCs3CrFl0rBl08=
  template:
    metadata:
      name: sbx-templates-unique-polyagent-001-secrets
      namespace: unique
    type: Opaque
