---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sbx-templates-unique-polyagent-001-secrets
  namespace: unique
spec:
  encryptedData:
    UNIQUE_API_KEY: AgB9vN6/+cP6uQgTYe4xrLo5QYYGLA/GyknhoYSSjyIRmIJTD85dAnwBRaEKcRRSx0RJz/bikKliXwBHokER+AB+XkiSWrN+HvCNZdmeV8iUuOFOG7EazFft89ZfmTCHcSkbT5Nhh1sljDVUhIKINYTpehNklHkt1+lOugnghbuEzIA9C3N6JYNKShSXq+SZvrjffpb3DBu1wby/sMn0sIzxdqnxhCrw+cwzY2Vs3pcnKPAuqageUkswDrbowi4US9e3TvTTJZZxLLukTtfNYpj4qSs9dBqP1eYKpMWLAMLddmKd35Vn/X9dRdJBBiPHIO/kclHFpthgTDoD6RCU5glQx9RIhMn1sXRnco84KvvzAjn+uKZe73PFlQ3HW1PBRh26kxT+PyUjHAUrSj9aHYevZYVl9TelhBni5zU7yQ0xcEXCbkMVCPL6fDW9KIowWUwIBwNTrVu/2GOyqT0BRKV5pC1wPGLvGdnQ5YJjjOTLfnSSI23GvcfRE0ZduWDkgayWRj9RXR9Zm/YiE2czo7OztI5LywCgPfrZLtCNPIEIWqNcCAIDxxoWXyfJ46+MFgDeNrO+lDcX9m16+z0D5S3CiiPg/zmLQpc2ubHOetxDBIPWdfTmkV2nLg483V3j4mOOLfQTaEpsURr7z3m4Cb2sVks6XuWH3OMTNv6hrF372lRpcAvHVEJxrAqat+hXU9xNZY88RgzCk74=
  template:
    metadata:
      name: sbx-templates-unique-polyagent-001-secrets
      namespace: unique
    type: Opaque
