---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sbx-templates-unique-polyagent-001-secrets
  namespace: unique
spec:
  encryptedData:
    UNIQUE_API_KEY: AgCgYBuOi+tYBu1DNSvbkdz9873rhnk80L856g1swomWl7BZ075hn8PNX4JK2F9C2zjeH8emEf7zzOdkF7NIrq6i9Vso1a8OxXsCQvmxGFr/BFYbNeyDlqd+LXOO/0gLH0qMLd5TvfIeFfFPFhgewiqoJLmaw+6IxmDusXdMCaGeX1vafjW1LPCPFgwOIdod8ESq5CuSf0AtEBExSp27c99/e588JG8fi0oZ3U1MX3lG4uqPGjsNANs6XdBn69/iXMpqCIHBEKIgcl+9s4vZDNYWrl3IiUTN6zCkVAW8Sow5BcL9i2NPQR2sRz/XatlYgD0zOU2FEGkbHTBkrzdOnIHSfPa/3s2QUdth8tvQW3jxd+38B5YXP+xnwz3aLrB+n5MnyH8sMbFi7UXmH9EJ8gl1MY8WQHJ7d6yjw1uuOTSUcfe+/IMR8oiYdJFcEy16MjUwdBrp38xT6cxG/g/ezhX1WKAIrJuEj1WNVJWeg/5vMrILhoBsou00eY3g8nBDqumd63LlQ/R4i16jIlkggbf7g+Aip5wL9Nptapr3M2L0933adBjw3TBJSMtZKxGrOelk7mSklZRJ7HKD1uED7FmZy6e66Nk9KvD0LTZTKp51BXD3OWQb5PrI5MijpC+X7Yoz8x0chsjlIXVNb4EWfqs5SqHgkhH8+0Af1I8roAcq8b9B0h6v7OZEnxs/ftN9S7PUY28eHdQslD4=
  template:
    metadata:
      name: sbx-templates-unique-polyagent-001-secrets
      namespace: unique
    type: Opaque
