---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-webhook-scheduler
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgB0RRXw3g6ao69Y7opTEG1Tu442fc95K5WodV6vPjNI9RFgjLX9W56OMVl+daWAaK7ndDkkTC7TXMe0R8OXOlAxEeHHwTWIzhbb70r5VYjBdwHUw1MKyRzgUr7mMq/d9VZ3VactYDGWfft8+qo8T8EgV6fQ1xjHn1zmJASdBe4zd93ynCXUSv2vU/dfFzyGs5yaneUGHhiH2gAFmpk3DffPaOM4j+nCuPNiBfmkoM7LJ5dfy5ERNz/4/82IvzJQaa/TobqHWtv7Z2Hdm8DqZinL3MOkmczKmOSihE6pr4YnK7Sdmb4xpYh2A1OP6JgYRqwCQm7RCOQKM/XXYdLfu9RlSnoP7WxnhyGZvhWvAQMu8LWXI2M2R2r2+UiujeazRDv7riYHuQob5ExEJaaG7Hh5jXOizchOL1syz/QUcC3DPRTD3T6kClxC5EtROhMcbYt74sEdjlUyJR93bYISbS82F2kXG7J0s6rYoxEt4q14aob09WWUGIpGJcjjvQPkxuNuHqRM0l4vX5NYNV8kSL2C96QXvZWHexEq5TqJACyXtf4TfRS1RHdShy0jXAzVY6vyCGKzawCg1Fm/dcVI3WibauGproT8JalGf1MMnrCg8Fb3k2r7KGHHqbmuhAMSsAIHP1vmmugdVqN6qvNJvZCUL4F62SaN8lr/8IN/phEbj/quglDq1fR779F6hdT7W5ygjNy5fGL3ntf/r9k6AJk/e/54U4onTw/kAWj6L5nR0LCflqDot/0nltUri/eMqJ4tvH8N9qrTTC+gYREo/xDI+cTM
  template:
    metadata:
      name: service-webhook-scheduler
      namespace: unique
    type: Opaque
