---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-webhook-scheduler
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgAOwB+UanhmuRK4G/QSWb413wlIV1YkZexRuwi0qlQWytXSrRWL/9wAg54cofLl0fNxSuW+ejdmE3XYSu0+xsf8WMvbEmyWkeX4bdgcqcfGLqK8c9TDlC2wyouwm7EL/2XN3PvrLLcoV+B8v7/sSWYhArJ9Sbq9rEOa1KxCgrmVoroPmhLl6dDgMxDtl31boejqKVflDYKih4+Iy41vMRfEliM/ehw1XvOxte2Bj3JZAGnf4dgsctMBSGCWX1phYD+xDGcESGFQHFBo9RkKMvphMNAkK1cZzuzGO2c5AAHIHL1ifN5VhnDbiWRefks/dP3u5Tsn+iecrEjq+579bW6wQzbeZgwqAN14OfNSkZlr6wJs2UWg7l2jcwerVe9reXz9cDWpDlGEecGdD0zIvbZELdQP+MJENz0dmosCh/3VBOfmCJ5adlNh/YyRLA0FWMMTh/suOsUw3WQ4/WU6gkBCEnr6sWwlTsDzKOuP0yG/uCk/VFV1AqO8lZvsRYdINtZPbutn84cEYqLM9TrQVlqs7r8EPKFfE7+qxBWCNlnPCtRzai283vDixtYGWGyt8cshLyOg5XzMyMmfHVWpJlPA1sacl4/Fo1FfuwvBAPnt+IeId4Z/sGmSqV5OjW7t1Iwy+uPk8swOUi6Pny8Jv9AASzEZeIJ4fIMq0sk++FcjIaSEzY/XDcrpy1/ZFJQSkjzXw4JtiqktUVwKAn4mGppzAnizPUKGF6PzA7Xqs9UzvInDiRtgLHmkK0ufYyBehPhlD6qbSwq0X5aL1fBwkLc9T3AF
  template:
    metadata:
      name: service-webhook-scheduler
      namespace: unique
    type: Opaque
