---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-webhook-scheduler
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgDp8u9DAZL8h/LL0OrBpn54eyjmgmqAlo9okxlnmQF+yGLnbUOmnrYjbRvm9U773GmihNq1u9YOI1BBQhtTjat+FnqcywBhhJO9e3geBZ0HRnL5VUicwiYRPBOiSBVZw1r6oONAjdeMxqB8Llq5pqkzC4NEzcOoFJ3Bj8IaJy6GcavTaE5Jgmr4+92hFLrT0GID/2JY3cWj9xLtkN8ZMwxDuHPi/bTEAGDw3RZqd16gmcm95jYp9PA1OJUcaNWJk5l4wYx57p2Kfm4gyET2boVuR/iQcJ/aFpC7YGiA2/c44GAhM+3zx9uKz50nGBMjLItnqoaT30K0tEiNSfBGG5RnQmxSdZb6eJOUDW7FsRBXF0sUmOhFCsTolWi/WLQU8091Pc49qLx+v4drK8YC658H8rLNjvpgVpIzXJxfHDx+PWoEfdz2JzaJaHD7+Ltd0LuKB4ym+2V44/pRQZGqVedQYfGzerYAQlhhfWLT8rT5XHN3H0FtnH8FT/oM28Staqk8BBfN+V+0XAKoNcrDHU0OjjLfXFByb7KoLaYAK7fxeoDv9DjMnam7NNC1Zj+BQ5YDl7QXcdN9i50HxHS97pT8HbgNssZPH+P/FzN567YIXiY6e24gVKaL6cNrz46thRsnTovGlY9l27ucJB1iL1Z7jWwPYvLT81WlB/p414E8deWGu23/hFE+uyzjfe+b8VeGvn3W75W2/6uWSjnoGHcI08I1xruh3/uV2ftC9uqZ2oytsHiuvb7m+R0O1WEpzcY9wlc78EH5acR6lLz4eN4hHXnB
  template:
    metadata:
      name: service-webhook-scheduler
      namespace: unique
    type: Opaque
