spec:
  name: chat-app
  rolloutGroup: frontend
  autoSync: true
  destination:
    namespace: unique
  source:
    # HPE: oci://harbor.ingress.pcai0201.fr2.hpecolo.net/unique/helm/chat-app
    repoURL: oci://harbor.unique.svc.cluster.local/library/helm/chat-app
    targetRevision: sha256:194aee523332634385f649f98b64e7f31e28d409bf72d12774e9c9c5f9b5e7e8
    path: .
    helm:
      passCredentials: true
      releaseName: chat-app
      valuesObject:
        global:
          image:
            # HPE: harbor.ingress.pcai0201.fr2.hpecolo.net
            registry: harbor.2.28.18.215.sslip.io
            pullSecrets:
              - name: harbor-pull-secret
        image:
          repository: library/images/chat
          useDigest: false
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/postgres/ca.crt
          UNIQUE_INSTALLATION_ID: hpe-hosted-trial
          # HPE: https://id.ingress.pcai0201.fr2.hpecolo.net
          ZITADEL_ISSUER: https://id.2.28.18.215.sslip.io
          ZITADEL_PROJECT_ID: "388746568834023667"
          # HPE: https://unique.ingress.pcai0201.fr2.hpecolo.net/admin
          ADMIN_APP_URL: https://unique.2.28.18.215.sslip.io/admin
          # HPE: https://api.ingress.pcai0201.fr2.hpecolo.net/apps
          APP_REPOSITORY_BACKEND_API_URL: https://api.2.28.18.215.sslip.io/apps
          # HPE: https://unique.ingress.pcai0201.fr2.hpecolo.net/chat
          CHAT_APP_URL: https://unique.2.28.18.215.sslip.io/chat
          # HPE: https://api.ingress.pcai0201.fr2.hpecolo.net/chat
          CHAT_BACKEND_API_URL: https://api.2.28.18.215.sslip.io/chat
          # HPE: https://api.ingress.pcai0201.fr2.hpecolo.net/ingestion
          INGESTION_BACKEND_API_URL: https://api.2.28.18.215.sslip.io/ingestion
          # HPE: https://unique.ingress.pcai0201.fr2.hpecolo.net/knowledge-upload
          KNOWLEDGE_UPLOAD_APP_URL: https://unique.2.28.18.215.sslip.io/knowledge-upload
          # HPE: https://api.ingress.pcai0201.fr2.hpecolo.net
          REFLECTOR_BACKEND_API_URL: https://api.2.28.18.215.sslip.io
          # HPE: https://api.ingress.pcai0201.fr2.hpecolo.net/scope-management
          SCOPE_MANAGEMENT_BACKEND_API_URL: https://api.2.28.18.215.sslip.io/scope-management
          STATIC_TAB_NAME: Unique HPE
          # HPE: https://api.ingress.pcai0201.fr2.hpecolo.net/configuration
          THEME_BACKEND_API_URL: https://api.2.28.18.215.sslip.io/configuration
          ZITADEL_CLIENT_ID: "388746593328759027"
        volumes:
          - name: postgres-ca
            secret:
              secretName: postgres-ca
              items:
                - key: ca.crt
                  path: ca.crt
        volumeMounts:
          - name: postgres-ca
            mountPath: /etc/ssl/postgres/ca.crt
            subPath: ca.crt
            readOnly: true
        routes:
          gateway:
            name: unique
            namespace: unique
          # HPE: unique.ingress.pcai0201.fr2.hpecolo.net
          hostname: unique.2.28.18.215.sslip.io
        postgresql:
          connection:
            host: postgres-rw.unique.svc.cluster.local
            port: 5432
        redis:
          connection:
            host: redis-master.unique.svc.cluster.local
            port: 6379
        rabbitmq:
          connection:
            host: rabbitmq.unique.svc.cluster.local
        objectStorage:
          endpoint: http://rustfs-svc.unique.svc.cluster.local:9000
          region: us-east-1
        litellm:
          enabled: true
          connection:
            host: litellm.unique.svc.cluster.local
            port: 4000
        namespaceOverride: unique
