spec:
  name: qdrant
  rolloutStep: infrastructure
  autoSync: true
  sources:
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: feat/upgrade-to-2026
      path: "1-system/5-qdrant"
      directory:
        recurse: true
        include: '*.yaml'
        exclude: '{app.yaml}'
    - repoURL: https://qdrant.github.io/qdrant-helm
      chart: qdrant
      targetRevision: 1.18.2
      helm:
        releaseName: qdrant
        valuesObject:
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          persistence:
            size: 100Gi
            # HPE: use gl4f-filesystem
            storageClassName: standard
          ingress:
            enabled: false
