apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configuration-backend-connections
  namespace: unique
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: in-cluster-secrets
  target:
    name: configuration-backend-connections
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: 'postgresql://{{ .databaseUsername | urlquery }}:{{ .databasePassword | urlquery }}@postgres-rw.unique.svc.cluster.local:5432/configuration-backend'
  data:
    - secretKey: databaseUsername
      remoteRef:
        key: postgres-secret
        property: username
    - secretKey: databasePassword
      remoteRef:
        key: postgres-secret
        property: password
