apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: node-app-repository-connections
  namespace: unique
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: in-cluster-secrets
  target:
    name: node-app-repository-connections
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AMQP_URL: 'amqp://{{ .rabbitmqUsername | urlquery }}:{{ .rabbitmqPassword | urlquery }}@rabbitmq.unique.svc.cluster.local:5672'
        DATABASE_URL: 'postgresql://{{ .databaseUsername | urlquery }}:{{ .databasePassword | urlquery }}@postgres-rw.unique.svc.cluster.local:5432/app-repository'
  data:
    - secretKey: databaseUsername
      remoteRef:
        key: postgres-secret
        property: username
    - secretKey: databasePassword
      remoteRef:
        key: postgres-secret
        property: password
    - secretKey: rabbitmqUsername
      remoteRef:
        key: rabbitmq-password-secret
        property: username
    - secretKey: rabbitmqPassword
      remoteRef:
        key: rabbitmq-password-secret
        property: password
