apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: node-ingestion-worker-chat-connections
  namespace: unique
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: in-cluster-secrets
  target:
    name: node-ingestion-worker-chat-connections
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AMQP_URL: 'amqp://{{ .rabbitmqUsername | urlquery }}:{{ .rabbitmqPassword | urlquery }}@rabbitmq.unique.svc.cluster.local:5672'
  data:
    - secretKey: rabbitmqUsername
      remoteRef:
        key: rabbitmq-password-secret
        property: username
    - secretKey: rabbitmqPassword
      remoteRef:
        key: rabbitmq-password-secret
        property: password
