spec:
  name: rabbitmq
  metadata:
    argocd.argoproj.io/sync-wave: "3"
  autoSync: false
  source:
    repoURL: https://github.com/Unique-AG/hpe-hosted-trial
    targetRevision: feat/upgrade-to-2026
    path: "1-system/2-rabbitmq"
    directory:
      recurse: true
      include: '*.yaml'
      exclude: '{app.yaml}'
