---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-ingestion-user
  namespace: unique
spec:
  encryptedData:
    secretKey: AgCgD1fcbTalDsG7dvosgBBGred64VbxDuCIhk10RGuU7AaTrcvkWd5c229/bYveWtoU5f/tvBoazA492ys2VzEjLaWZRm/1QJ4Bc+J8qHMlxfRlpPOD5UqA2/7ga4WeGV8UuVZ3L0V0doUCIXC1eVcKv7Z+SWa3+7MuspOHJRZmkPuf5cGWG9RPItzsZgKD9iuz52O7fxUxpwOzzoXGhdw5VPuz9+WaHVXgqaHQ01RpwAI0qI3qBOIo8oTlsew2yqW3lq988xbcYnBXr2ncGTfxNgQ8W2CLNnYrOnNdh+C8kyXU0dc7ygiQndMeq0WcjM+rEF12fkrUPik5PebIP7MFLkaKWZi+C40+2nJPsREb7BWK8Rf3dGmZgIg46UQtuez/VrgbCTlThkkmhTNbt0Q1Gof7EnIWcHfKhdtyyMxlUQor329riZp7pnEm7iMRV59cF/mTAxtNgi6SmaZlRl9XNlxziaKdkiHWXxFzAQck5oesdRpGHtRdZEvpMXV1m/vnqmGyNxyvkPd0yIH+QiHria4OE/GY36ijjtVbz/i5pPD1+FPsOt2mT/H/jCFOX7myiORVYi6XZ6aDefths17zu5XADoHi602KnflIAplAumPgkKIZCwRmuC3WmOj2ueOpZlECWCCNk+kGBoJwMXQRASTkv7aucVcTOTIubrADMf5dFDpV/RpVTRxgngvxwt0PyjEQ8hOgSFpXj45RCsdPfzeQ7w==
  template:
    metadata:
      name: minio-ingestion-user
      namespace: unique
    type: Opaque
