---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-ingestion-user
  namespace: unique
spec:
  encryptedData:
    secretKey: AgA8mxAscX9eqJQcs9bvCJFojQM0n58BrLElhP20mrXXLzhqpWg5hadRDx2Mbu9ysAP2VfzDbaDXr6HC8TTfawIQBk2oHTKb5l4SUhCN36hr7A5GVpf/34EkBqgB/JuBcU28ij6ccLKKXsO9Cr2nP63s1xUlbGuXeC3fXfOxtzT00zAheojIoYN7XQY258nXmItgNMWuTK1ZMzlIvm9mxGTu5Rm4bFAnLPYoLDOdnysRJgSVUaytywgMycccX+UNcrdZt9YTsUhsxZDDQBh4tYu+cLvVckfZj0nBwQx8rLKuCrgccwoEEdlkVrIbeW8gLKhhPpnSJqF/jzjs+CyAa/k6UukXd/ywyye5D/yhx+FbCs+q0fJvy7Vz8p1F2rnBpMEyV9fzCppm3M3lVjnjnaM0B0rfCsnfvAxm38j1HE1lJAozQv6BzWG05LwTJhtZx3TIQ1VLKl8d5CwqS3ogKYC1Vixuaf17Z3NAEqBTRKQolin6e5I3dbPS6rb4MOgOsgZV3Yj8Rf/WXyN1iSWpy0L8iGWtTT6UjpWCFeymamqlJiEhdNIVIJCVPUbFG7zh3uXzTmXH/rgmsWSPPTc1JdftZj8tBIWtXHGTlEVOfJ9XJaR4w4swsK4YIiHi5+PQbf0zfLqThXAZiaNdTxnh4dmBj80mYFTLQyXCABZ08cgzE3zY67DBhuQmBbUakOB4cv/18b3XqssiaLmg7yMgcT/2dIXx+A==
  template:
    metadata:
      name: minio-ingestion-user
      namespace: unique
    type: Opaque
