---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-ingestion-user
  namespace: unique
spec:
  encryptedData:
    secretKey: AgCDlv6cNWfVBNjG0gjEsY4FeYXpv6StBVvF7c4utgAtIxg61Hm19mK4anK/PfmmCagVl78xKZGGQpz5+9ze8tKz9RE+XS3CYvbw26z8Yo87ZCic9Ch1kB1eLQKxUXPvpUW9gDP0hWmoAA+MHzS2PR7+UIQ+wURG/HVdKrm26niqwzl5H4Eu1sR54Unp5X7nA8XdJax7TgLf8CHGPyK3YxIZGEYIKGVJw+StiJnGVaOgoq/n3+0/AYpOKYeLBdNrjc2g9n+3+RLzjKtbLPsLAV8apMyPM8Rcob0swqgoG6NkjOcq03GBXXYAZOVW/oKVQF4rH8i0qHybZL5ebWSwQ/qMwaYYDEBALx74qfDd45btkEGyLMTld6W1Sw3pXPqplgNnKC56albLbgwDHVpJFU5ESCJ37xi0oJDapvv2ihOfRw/gyCd3oukqLPNpPTSzKscFoHmzMz93mjr/Kd5HInMf9rhCjHM0LRM331ikzRZU9TIjOLcg5DHuVFarL2+/k+8jAOxSIaF5A8mANQ1extcsjAUhdKM7EKg/2hV0v48Ls8C1x9Hz2UGBII6hjc5ob7UM+8FtN5ud8J3BeortLM+R9GTfpo9z3/q/SwomgIfVbK5cv37kIOeNpk3QkaVfK7EMhYjIjq8YOUnFFigoKm66I0avswPRd8WMlD/yD6mhZXQJbROlwB4fkKj5qfqpsNMiwr06Xb2wFLg+NCcroa+JVnthWA==
  template:
    metadata:
      name: minio-ingestion-user
      namespace: unique
    type: Opaque
