---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-loki-user
  namespace: unique
spec:
  encryptedData:
    secretKey: AgCwHo9lYDJ2AJbJSETBdo5OrptPK0I4cjNwfgyK0Qf7tuIsu8oVYWVpE8rA3I4IMzg2dXEq5Qsskz9Kzz4OwoYlRBQp40a4v26SaOlmSsOayLoHvou5ism6pgdaMXOpvpRwszKtaPhivjHZvYI/VV3nKEXNFcweDbvy1DRSWgkUjdwBFuNHgICEEYhov+Q5nkCIm7PZU8BWGZMYTV7coa9RC0AdjLxSSVT+heNGJywyWLqPPShO/qfcZCJilWEaFnsABNYDLCtYtngUedEo6bx8M443wW2xQQcKs7sg/jcJaPc0k0zEHS0YeVmv+UyFSHQ7DE+VlsWj9F8kHYsqsw73vxt4iNEpXPsiEy+f0EXI14R1OJyLx6WM5mzj297nVIEMR4YZvnDGQt3uJyu0DH5iGgUURTM9sRhNhw6CsHLlc22ApBMxhsZN29bh1b8DYkps25ZjaCpXBcnA+FBnKos8X3bys5bx6ezIChjOFyORheUx0sNs3AK3QKudqzmsdwD5R2vo3QzR39xVuYfWBAVkk7ZSW4ACXZXjYTKzu92zn+2eBIuZJS+0B8MQ/DkkBRrFRX4R+T0+kcUbt3nKltqJDOAEl4+4DLiLkeIAvUY2UEgHbrMXYHnE8aX/HktJBaEq80RzA9IJ13rm7f5bmkf2MXPaedRXfHJD/DN9qd3+vrLa6du4Py5TvhFI1uM9JOB5x/9GDLfTjkkU6+GyVtsadhefIg==
  template:
    metadata:
      name: minio-loki-user
      namespace: unique
    type: Opaque
