---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-loki-user
  namespace: unique
spec:
  encryptedData:
    secretKey: AgAkNr4H55YwDvZlUdhaZ9AK1D1F3TRdw5a6tjQHI4jm4qnNB3xfxfjpnFIGoFrxLXvIR/ilWK9Cy4FanyDUeEXGgxlqEsn0fzYtZx4Y9CEz9E/8710B8w60Qrd28yr1jKPTv7xbUqz9R693KhEUnKacbk5YC8Dtq5pbVvkJBtignmCrUUiQy8kZGJKdLpRWmFWvo6PTDAXpgh+caSSbEMCLq5cz5AEJDce/YK4hufgkPxVNkPzuncacdX7os83Q+gOxBMQFHSLaCB/d6MLCkGUpSiqrJuZ738EFre/8pwzzdH2pXc6DwHo6FQnuAhpA9BUtccXKhv55s5vd5PtPdhKrGXEE2A94zEtV6QvJ1X5jinGnYq3Ta2TzYopXPN0yXiFL/2yj6VKmbcbtsVM2VzK08kgMIZ9Gtegsx6Q5MIXlVB5jhZOXoGoclK+934R1vOuEFnqe/pn3epR8RbZycBitL3NV7TdKD4zEoD/5qPEX1WP4umf0cicNPphCDg/zzkAoAdqh3tc3qsw6K7vhB96I+xMYwdlBDSGaAXz8OQ459x+mH2UQ6k2RBNbDjvd/vVG/ujZQGgQmR++G8s+siRcfMGkUzOyIvxhRCdcQQlIZE2RdHr56CUFTiPxlxaNrQnICxXAbB/HQ3OWnzuzcRR3Z41FqYCUDQ5Fw/Z0Xyf0yD1QHMtDZusApxHahlo+xMUazEDtk8glP9zkjpR9RcoYC+lrKAQ==
  template:
    metadata:
      name: minio-loki-user
      namespace: unique
    type: Opaque
