---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-loki-user
  namespace: unique
spec:
  encryptedData:
    secretKey: AgCIK4O8mVAxESwAQDSdxaLUnHzoFsW3j8x+vieUWICL8sR80E2bFNLo7GVun0t24GA20HjvypEBzKTnxal7NGpwuO89caAxYbZQmazfWuigVPCf5a3M8eYtZrAiidOhr61+xtz5G0YaQKBdAGcqMOjY7UWEzI2ZYwvVq/Yykse4p/C7/0dorpxjHxTKZH/ynQnS7iFN5sOaVR9nuLXMCIEaYEOhQTBqHYA336mBA1OUHXvp1+4kL3TjU+a0PJtRPKDjwpLlAJIzX0Ac6iJ2ch4dGcq8wtFbbp0JJ/QLgFSe4Q5EjbZRLv1PQbt0DvjNW3iljYq1i3ya8WZUdP6Ft3Dkc6XURC6iwdfVvL/A4MoNz/Kv03UgerE2zPJXWZz87yJCqoTkoeBIGPj6pjVSpF6jKAbMqOJwRweUx20AveWL7JildsM/eLRFa7lUz5RlG1kvv6wfoVBuW5VJfeN5sDYdgP9Q1FFJriN206gl+wlpcYMPuk3KyxXeBLeBgwJOMkMK+o3lwcStPW1rqvmcNSDt5nBhRIe2wU2Igbf8l1r7U22wC8koMHEsCaxtjfiE6TCKrrPlWxwZ1uP9BBiiq+hMce8Th7PuLpgME3V1k1T1Ew0BUcsFM7/dtD6iSuVy4RYoZvdIS5Xqry+KsJjkjAk2ENskxQYpLi/Dou8HwkOaqHkHGVemn1OQBiEmemI3c2Titoo+7R7SDHjL/rekzh4qwplDGA==
  template:
    metadata:
      name: minio-loki-user
      namespace: unique
    type: Opaque
