---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-password-secret
  namespace: unique
spec:
  encryptedData:
    rootPassword: AgATkRE3qimVWhWGeRSxwyUkJX/dfPSnMTFU2WXrKzakHVgFvTqrfbvwpqOC3Q98+OSN6yH89jCRafqA3Hpc8e+EKDBpSCO1qtMJcCzKBtDv9SfMFjKH6uo5TUPxC/H+d2l2khkEgRRCkPbDQPmI1iH/WmQgOjBrpEDIXSmFJJSu6fuRgW2Exf0aM62Qu5mYnvzM0OhdeN4oV82Q13fbz++ccdNVWiTP4UXSU3rNy1fZXbEqSlHqtXhjTeChI3Ol/T+5+Gfre0wW+6fvWIvI3LMFR4xWb08sIZ0lAbjN0i1rKY70AJBVnzTsT2eupW9R/EPJVj8OeIo0QY0VcNdrCRyLmsJe6hd7syJkcosVGNRq59Cs3JdmCah7VRG8LknCDK1mE88Bd74aV4G87NUb3sd3LjZ9ZutBkP1FmJ29LlzpXNO0moe/1SJixzZa55ggflsSMzvxf7696cfVqX4it9V+DN7fLO2NI6qEFK7SJYiDaGg/YIbQkAHY1oO4ftS7iFjHvh5q3xlujmpwKgKgSiOPJmfL53wJkZwAqH+DSOPNJQW9rM8FeD925eZKuLgUJXk9czZCYM5fJh01PFJIEp4qsqwWrqVZRxtFcUGsygPjKI8KuALVK+a3Lp6gOT2D6yzO63TDN79Zg8NNr9vm5hswGGJBL2zM65irQS0tYBeMidBn+jThxy/37cSFT9nZ3IiP6hlNqaRFhcvHYeqU+Kb7PPSR3Y68+MrT6UnYCumrYg==
    rootUser: AgBO/FW14vRrnbS25EQA7jcqLIf+Wm4iukhAY/HOd22NrVZDXjqBX9rgLk9fddAVc2KRmWDwxF87wo1N1jDTt8jwsbeBWSWlpxFzHhx3XzzAeX+kHQFWRXdeLcqo8utPIAq2R/lm5gHaOKgnJrcqug8k3tkJh+Q29KwnSZQGu7CV/IXwArGkrpO0NVy3cmHsKfvCfXofN7cQQFP2kkNVzYBDdI78BmWhCafe0kgclN2JtTsif3SsWUKZsKIaqP7EaKyTYpLfRWH7yHyL8sMFNkrBh+grnJj5w14blY2rWayMMSEbrEDB8oNmiMlQYf80r6qaW7I5uBRS6R9KObeTkUhAnQfS5dCGqhLR5fJQ4BxlzMxKERZvXtlB67l9TER6doxH97ab75weNWu7nqrGod3azMeDCgjdoYA7nE5E1tKSUrPrLekfPTlXcFtk5y2lHG5UhU/T6tGv7epFvu7MKvXSwx80isTZf9C2Z3J36eNRo85UdK2UF2MjzSw7ci54+AkHX3GNdgoQRs8mUS4OfETr12Nd7k7g2gDawE0/dZ9iSEZapGJTeixN/CR20TrsAGqWguzjohhYXVwuTRMiN807msxjnllLw3UCxOd4b5kGYiB34jAjQ2b22U8sS7Ct7zj04GJ9rLiwsAdjVCJNUUHajvpQMdq4FZQw50j3uZJDXhgEinoryC3ycKZ3IzUCz0OrW6/ZCA==
  template:
    metadata:
      name: minio-password-secret
      namespace: unique
    type: Opaque
