---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-password-secret
  namespace: unique
spec:
  encryptedData:
    rootPassword: AgBy0Mb3Sfv35YDhQ4qMKIt0RbLk7kiCeUxJpwyqmll2JNqGYAwC2mvoNb6gbKM6DUPFrNcT9Xq7hNM3pH+/EvOnV1pxlwp/p0XqYndbXgTz4lJanS7AoP4V6RZt4UMDF/LMzDF3UV0Nt0CopondO7YdmZdKtn0kFNkiAE6nGHkjZKRNSERF/34Lreqam2gkEL97orFOO6lzsQBS+GTRiqfVL9ddzXwAsozcbHN6rnJvzd4PzQ7E30UWxJ2j41THlF3GZZiMJWQqDxd/p7BjA4h49+JZwPvZmoUuQhcG5km9M2KutSKFTOXM+fO3d/jr9RlVVyiZyUUnsMtSu97k2Vxin35PQw4FyHcyEmwJ/sfliD8td7E7myBlq94/IyHWv6r7JDNzG9k5Nw4V9pLZyOTDEMQac1vQx8hY9PMBv6wYVvTAsyadOiumJX5QOybid3B5wDls7u3oVzzBDEAyjQU9SlClnMdTyXt5dbmEwkFzJJ21Br37P4XMBqqEAJcQRTr9+y1f8LnJ1SuA+iLqU9M1T8X/0sz5KIOIBwQLmr1CWZIbkBDvfn4byNHFNzChWyY/T/QHsYDAgbQjlzvLyZiLQXe1+sbCRgyor9ZdIsaIXEi1oKJnUepaHNSPK7dwHhIKnN+AMcrvRYkPkNfjGDmQ5XpFqkCV4rRG+g3fACvRiJjjDINMFq0zXzgc/dJtRWLzt1qnuCtHhQBWOykjOiPMBphRf+u6ThiLAaL05sDTKg==
    rootUser: AgAR9mWoI66x4CrZuDZv/B49y+30hElP5bGtfLVj/E76CHrBtGzh6mHdb+HMDOD+DiiT9H2/LpkIAH/bavEXm89+yck0btxBYQJgOw5aPZ0lgZ7UCQeCwWbplVZnjjfXikpzQe6m7NZ5iMs/yqbJc+FK1JHyPQqf3t1xFdtkQG+gBzbinEpZ1+Mvo7lhAPYTl7ZNWTehXNyVDwiEs0rag8cH3aEg2COItmgq+yJDKdOt4fqAIyu6dIDwN+xlANV0liOShdOCbCSjD8vOSzKGxJzVg/JHTFnRibeK7LAdVOC5nhAuTvqQoDr85zF9HmHqw5wpjPmbZ/DsOmVINoeunTA0VKeFwmDbNbVEIp/2j8oJ22jHSiIz17KldRUMGfSaXes37BBE9n8BYER5MV2gpT2+QctcOuHSaT9mOULHbt3ccslpRUSl6wp9Pb/pGe3B81VAy9L3sgLbmQoY2ki4eTVi7jR/6S3jAzBRw1TQVKpP4nMiWRdHTBfynKsJI4gqhv3c2GcpAS1DGk4MVDR4C1yH/GxEQnPRLbl87pMxyYrUnhbIshqjSbo7cvV/oh8msauxgag+G88j0FXh3I+p3+4yu3B4eprfmxKn+Dqy3SS6PIOc33yXAeOTN9K8ByAja31uSLEaGYmv2/+DYAUvArV7P9ahWXZow9xAwxvei0ee27lQsPP0cgFUgQxW6858ZIW66V3Pjw==
  template:
    metadata:
      name: minio-password-secret
      namespace: unique
    type: Opaque
