---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-password-secret
  namespace: unique
spec:
  encryptedData:
    rootPassword: AgBCqdPl9MibkHkniVRhvCaKaIojXjfySfmz4WYMrug/W543XdOS20NVsqtX2Ut7g8A4hll6kRIErjttATZp68PB2paNuWZasmndXP/r9IZIoj/107Nyt8YbTl/8ksJsnNyZ/yv0tHXU5hDgsReQX6gJZ6YprNj4KvE0xF2jDov+Bc6VOmaETnQK6flONHR+AW62SrDsJgBbkQ6veDajFnlPq5Ty0WLgxIOMCpkKp2L6ACngcDWJW4KJ2p/OfyMSGF7R7MzrMRXvCyeg9d3SksJN2/hdHB7fcoYb8sn1BTZh7ueo/u+QTo2i8Gy+v82M3isHIkLpvWV/HqCWZGjkQwbeH3vaLuuiPT9OEBkGiotKdMmIFk7lKZ+d7WpW3nrJh+ERD65FnbpeGdbDXyFPMnXV4qkoF8btduq0CvNU/s0Necz1aVYk1eb0CyBcPiAUOMJ/rbm7N0CxLOPymKMWcF7iXPGXmeVoYUIbj+kC2pohj+cJdeTuKcZOitzT40OJv5YLlycXYxFZtZo+fGOpJMwvz2eHaSIOt0FRrabsaPnCJy0Q5003QIflXGr4wOjhb/021Qg7dMImOwQUseyfoxcHShVHOnDQiarvRrNdeVOziHwmVwBw9FYOJ4OG38xrlRwaICuqcYMKhZh4NfTmiKVmJyqtUQ/cU8LCIMKCBQtFe32nakDwIJ1OsfxqU3G+wc8ys7G92OgAkDjbj3NLRdtb7KQTFlsyoLgWIJbWyCCSLA==
    rootUser: AgB48cAnhYtguwNdXIcUi+MBnqFZ6OqvalAP14yHLMGAacbUd9uNqrEuWO/8GX1xWMZrj31gjyHa2GSPL1YLHFu/ENmMmQ+49K5O1GYV+92Cl1jjgjl1bLB6GPPq10Oj9GvI6/pCgiJhc2fhIKrnd2VJ10TVsonDucJihCw8l1bzrZJGXfihuuIvruPwf3OqSjQpFlwY8+DHb1Wi9KZwqruDVVetHikw6wy2zFZnkJImv8pkVfgSAMP9mhf0mv6G7YCmIeB7PFZ5lzd9j/wZ2ID5O5OP7AGFu0pCAxCH2tq0OspdBTi8LJyl72AFSPD50CW+XDSAYrZgq0bYtT4G9oT4Pe6T+sSO9Rv3B5kV50YXyablVxysnVA+TupeiOywwCjvfc+HoaLrCkxIVoqEGtkAcy31N3zPYzRdKeUxmmbj0VnTQeYS1N1McbD1VdU5osfFUVxJoAvOXp2nlH67SPA3pvj3mn9s474gJQ+WyQxnuUO01lqMszjhKbbx12gksLYeGwQwk38Xctqe2fNVZeGaluVZRTAP9Hi8eBUP82mVprmAVT6LBa0a52btEX+ShpFFJWvpYBZDbn43U7qVCmkfH1qbsfDsbebG/fSXr/Cm+3R/SmQUrSVgT3o4j4hYrr45Tsl1JxhhPWYflRm0bfKvl97VSvm5tFTD1je0JlRXy52+2KyKDVFjn4YbZYzWZVenW4Wznw==
  template:
    metadata:
      name: minio-password-secret
      namespace: unique
    type: Opaque
