---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-loki-user
  namespace: unique
spec:
  encryptedData:
    secretKey: AgAczlV5FReDaGVJvnXtJNBMJp8vg/l6sTHJgrKfub8ZaQgX8nrkpngVB4J/oMbxl7w2wvcYrQDdfYE5jVRKUjal8YKBMhsoIJeOQUmvj3a40/6ML4kfTEDabx5Uzjy6mz4A6wRG+ompMHoTm8LZTjVv3c9xBMBv1Ws6LRGPtGcigbOBYJMnrG85Z7z5c0GdZ1JmpgZTI2sl/M2Jng/jKvNyyYBvjGkqg9R81dE3XIwTNoSkGjzA6wu6F/1sqydCWQxaSBVWhLsXa6yVNEct3etLaNJ0xITCyGoeF/iSoMDRAlmHgECq8VELbMhxEi5/uoIrKtS3Ns/4toy76zyo0Y0iHVKkP+4ssCTsMFn1nR+yLFs6lZncJ5Vo24s3vORbkywYJ4Afh2zUk8Z8LWXvoU51iNEMIba2x+evz2+2sDqwD/q89MUZEmChoB3CYjF9VsyEv4SiHUtnBfa8TkzrS7x6HpKI2H7iDvRkIHD7UAztxAurRGW9peF3w9elf4XZufnhky9ED/Idf4VULpJthUbSt7Ud+BTZ6i/W5bxEr+TthxZ12Ga8JLK2K6eXpUXBJQQMEnJr3ZRryk1WqaMVNBhSLzwcOL0WNSu6BlaHSjWlhxrHF62a7uC6ajLebs99pBL+H2hdAHlTPHmM23RnhHKh7ubWQ34i+YpCESL8nRtVAoYrIiCurvqM+87k3xUp7sqqHEdjCIKr6qyvGBzbCiXK+5mlxA==
  template:
    metadata:
      name: minio-loki-user
      namespace: unique
    type: Opaque
