---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-password-secret
  namespace: unique
spec:
  encryptedData:
    rootPassword: AgAjmukZz7WEWFbOMPowb9J3tvYNL7sTIN97djhhK75VUY1ah5XU+uuSLQp9q4JNveE+62/nrC0d7XQdsFqjwhWhcBrc0O6GWukcleTKOmhtlO6FgS8vuGv51lJqX1kVGmdOSIhouaBmQ5aLPNzb42wz22Tcd251SgAEA3CwHsNKfCWA9C9HcfiFRzYTXFFsYZFXlYKnvJr+8pQiorOPSLsrh6MSbzAnKmPzHfIryoXfvRAyOzOXq1TSvMcVvuFIOpEEFXGto+HG12WKMMCWwRkSw5AXA0JzdiUm4HJNcA3fzRBXv3JgDNclcARSfcTvoVxrNuBhN9ypshDIHQeVOBXkRWdnjCq8E+NiViiBEvG6M8CcEX68biK4BOlqzw+zYJhHz0mbsWe+yGQgPqFb4Mul4yl7czWSE6pRWq8KCFHZDM6KyoCMv4g6cJc9pEAjH9U06VxfKQ+fZj9GH4Uof87zuJcako/TlCngqfBprhAMeZMb/30PO0GJ5opYIvtOrNAQj8VOyzNzlBbb3ngh8Hd6TX/ZOR86Rs/kd+77xq9xT/VMlN+vv8gu4dBkGMLbka07ZZ9ZQvRUmhB578gk8htiBHnqlcJ9Sn49qGyCknrdyACQxtP3Ny6yJSwqe+s1ePZS34kUQneQlUqsnmFP61zdgNxEX6b9Hd+/swj2V+n/X+aiiibek+tagTfsLXAcDDGlPhH9OHT399LBHcEa2EfqLMmQehFSYv7fBS9aPjHQhA==
    rootUser: AgBvparPop/gQF6dLByz5STHBKtbP/2v3uD5kYAdkE0WfPjHhS+Z1AHefe/ogecAk/wvU65c+bOuspXp++HuWCc1Sgp5AHNx/7wZ5r5FYsXakgkdnnwA4GQrkGoPSGDwF+QBHz3Wk12PqAPeryVxgG33ZoHroSSTrqMkJ0K2ZS9ccjDMKKGmLtloZLhhkNHhBdO2DqB3JWF4l3PmD1q7LQuHl9WZQKgxUM5TqXifcHHwLgxywdtt97h9pGlpu7Lr8WP68SKJ5hlkOJ3eDEzrEYyQ/+Kg7X2xTt+XdVVLjb5UC8waY3GU5/39R8biWQk5pqm0SCdNqCjhu1OcdNJnnK42vD9tgzJcZWKEI0zpf5wMCx+zgqJvIMq4sGA7DK4aD8GTekioMoxU2Y8cqH6rMhP3hP15KkbIw1jAMy+E118onlHt5gEqqC0koJqn7ndBRwGOWbkD15QohsLJ9WOP3cmQ8ZWnrnJdoL6635JhNLTZi4cqGDlu8InrZpd3475rZAphuTl/9cfFgu8/04Sd/Bg+NUyH/0Ng+lpQUaeqrqnW1FMeJXcnWHH58edTgsYtm5Ai5VtdJsIMhqaEayEPqHVhXhLZvOfK379tWvJqx02OOlqHvBamwC23D7IfN5aILdUfZ0puAFLfFRXMQM3EY+yPNCJQzIlwVpXMgt3Tdr8AfJM8+knGnq2A/Amm14HprWBZy+6+ww==
  template:
    metadata:
      name: minio-password-secret
      namespace: unique
    type: Opaque
