spec:
  name: loki
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
  autoSync: false
  sources:
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: HEAD
      path: "1-system/2-loki"
      directory:
        recurse: true
        include: '*.yaml'
        exclude: '{app.yaml}'
    - chart: loki
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.29.0
      helm:
        releaseName: loki
        valuesObject:
          deploymentMode: SingleBinary
          loki:
            commonConfig:
              replication_factor: 1
            auth_enabled: false
            schemaConfig:
              configs:
              - from: "2024-01-01"
                store: tsdb
                index:
                  prefix: loki_index_
                  period: 24h
                object_store: s3
                schema: v13
            pattern_ingester:
                enabled: true
            limits_config:
              allow_structured_metadata: true
              volume_enabled: true
              # 30 days retention, matching the mgmt policy of the storage account
              retention_period: 720h
              max_query_lookback: 720h
            ruler:
              enable_api: true
            storage:
              type: 's3'
              bucketNames:
                chunks: loki-chunks
                ruler: loki-ruler
                admin: loki-admin
              s3:
                endpoint: http://minio.unique.svc.cluster.local:9000
                secretAccessKey: ${S3_LOKI_SECRET_ACCESS_KEY}
                accessKeyId: loki-user-access-key
                s3ForcePathStyle: true
                insecure: true
          singleBinary:
            replicas: 1
            extraArgs:
              - '-config.expand-env=true'
            extraEnv:
              - name: S3_LOKI_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: minio-loki-user
                    key: secretKey
              # Keep a little bit lower than memory limits
              - name: GOMEMLIMIT
                value: 3750MiB
            resources:
              limits:
                cpu: 3
                memory: 4Gi
              requests:
                cpu: 2
                memory: 2Gi
          # Zero out replica counts of other deployment modes
          backend:
            replicas: 0
          read:
            replicas: 0
          write:
            replicas: 0

          ingester:
            replicas: 0
          querier:
            replicas: 0
          queryFrontend:
            replicas: 0
          queryScheduler:
            replicas: 0
          distributor:
            replicas: 0
          compactor:
            replicas: 0
          indexGateway:
            replicas: 0
          bloomCompactor:
            replicas: 0
          bloomGateway:
            replicas: 0