apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.unique.svc:80
        isDefault: false