apiVersion: v1
kind: ServiceAccount
metadata:
  name: zitadel-init-sa
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zitadel-init-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
- kind: ServiceAccount
  name: zitadel-init-sa
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io