spec:
  name: kong
  metadata:
    argocd.argoproj.io/sync-wave: "2"
  autoSync: true
  sources:
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: HEAD
      path: "1-system/2-kong"
      directory:
        recurse: true
        exclude: '{app.yaml}'
    - repoURL: https://charts.konghq.com
      chart: ingress
      targetRevision: 0.19.0
      helm:
        releaseName: kong
        valuesObject:
          controller:
            extraObjects:
              - apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: kong-controller-environment
                data:
                  CONTROLLER_LOG_LEVEL: info
                  CONTROLLER_FEATURE_GATES: "RewriteURIs=true"
                  CONTROLLER_PROXY_SYNC_SECONDS: "15"
              - apiVersion: gateway.networking.k8s.io/v1
                kind: GatewayClass
                metadata:
                  name: kong
                  annotations:
                    konghq.com/gatewayclass-unmanaged: "true"
                spec:
                  controllerName: konghq.com/kic-gateway-controller
            ingressController:
              image:
                tag: "3.4.4"
              envFrom:
                - configMapRef:
                    name: kong-controller-environment
              resources:
                limits:
                  memory: 500Mi
                requests:
                  cpu: 300m
                  memory: 300Mi

          gateway:
            image:
              tag: "3.9.0"
            extraObjects:
              - apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: kong-gateway-environment
                data:
                  KONG_LOG_LEVEL: info
            envFrom:
              - configMapRef:
                  name: kong-gateway-environment
            proxy:
              type: ClusterIP
              tls:
                enabled: false
            plugins:
              configMaps:
                - name: kong-plugin-unique-jwt-auth
                  pluginName: unique-jwt-auth
                - name: kong-plugin-unique-app-repo-auth
                  pluginName: unique-app-repo-auth
            resources:
              limits:
                cpu: 1
                memory: 2Gi
              requests:
                cpu: 1
                memory: 2Gi
      ignoreDifferences:
          - group: ""
            kind: Secret
            jsonPointers:
              - /data/tls.crt
              - /data/tls.key
            name: kong-controller-validation-webhook-ca-keypair
          - group: ""
            kind: Secret
            jsonPointers:
              - /data/tls.crt
              - /data/tls.key
            name: kong-controller-validation-webhook-keypair
          - group: admissionregistration.k8s.io
            kind: ValidatingWebhookConfiguration
            jsonPointers:
              - /webhooks/0/clientConfig/caBundle
              - /webhooks/1/clientConfig/caBundle
              - /webhooks/2/clientConfig/caBundle
            name: kong-controller-validations