---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-ingestion-worker-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgBsf1cs66p08WiS1vJ+kOmT1vSSxS8ZwhNXvwn1T/9A3ytd9HK0UqGpUuoaLim/IHnN/3IA9Fbih7NX29+HO93fpSVLRooUlJYHJnOEUZAsn0hDLmoeEi6iEM34K6Ar3t5JKBdZ7kx9le8/sdxWU9irSFyHPktl8BPaLOaujGuSlgdHkp6jb+GNzoVDUABjW1S34xo0B2J/+hTlDo/gaq70T1Yh9N2qA8wA1eF4NmGpjXBtPaA3UgPl7PrcnsQQzxHl4EJM6zsDgC0i3U6/hU0i1wNzIYk7CwQ8ik/Ww2nSTTQv5yEdgY2w+KshODj5db71BTJIYsspcCEXxuzY0xLT8I1vo7LocjRtfCQ4GxfHFjiX+zzLKyPf3DBfthqdaIIxCotASWDlENoviLy3fwHXDiB/nO/uqAsHAknBCetTI08qZsz8QWQDAijyoC0rLl246HPUGjhHF6QJekVRbfSPjfzByPeXrVc4VEBmjh3chBcscfVuQFPB/hZCHfu+dK7WJRAYkQxCZL/pkm1ly2elv3FHx2F2Q9ZIE92BA+H3tmoylWScK3p68TSV2vzKEaog+cd8tkKEd5gwnvXYXkvyS4++K9Z35pmjOw2KvFK04PzIVsxgUHugdD2oHU9WOb4YIuh3Kw/uoZq8XtU17nuf6ZAw365mcVsq3jsCxHTrQY+IqFK6GiaJoNP8sfAZHek=
  template:
    metadata:
      name: node-ingestion-worker-secrets
      namespace: unique
    type: Opaque
