---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-ingestion-worker-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgChk6NiVUV2XSdw7AgWZGjeDCJxxYIt/VVp6IBcdnq5duKBV6HtRRInBMmC1wULYwiEy5xazM94YqlSGlBHtrPKyFKLJcNAW1A94gSwMJgrigE10Kdi9z/c7z93Hhz0zagmnqvNwxggWpDRmr/fmaGdwU2WLhzp6JwvXcbJM/YiH6Ev83rVktxJE7Yvo2iQRnPkRT3W8vkgWk5w/OGbv2ibyvQQHJ0KTJhVMdknCLn3KYgh11t4mwD+Yqt/m8bEwV/uzQAU8DgF8d77+Zu54dcF9dVpbGO2ZkSgapqnHpjt0FJlQVpu+JYHheBx4cob8Jpfj1qT4bz4utyj6MWUfw+8cwK3NGKylluT7Jl6KMLiNXfW2Y6V8M9yqVQAn/AT5Hf8KXyafjeTWmQom8FrUqPFyJeuEvc/jopr7VB4nwZNECptzqT4BX6VepVDij2Fo60W/jriu31M4paxrL9xUxO0bqGJaJyz8kXZzMq+2EQG9QJYArwRzKygryb/TwFpEQiIJtdQDuqlSUkofzz5znbq8+Gokc0Nuw8I96BXFZw4DDGLXEfi46lOfrrb5fhjPKR0q3vmAunYsbgZsh+v7fQYItZ6aCoI47XKQJXBKlshiaA32w8O5M09e8mzf9BOcW9dqv+ahGclyX15QeygO+g1E/zSBdc/kz0y8rA1fDthldNFL3IoUB9xpu5yrQkM2aI=
  template:
    metadata:
      name: node-ingestion-worker-secrets
      namespace: unique
    type: Opaque
