spec:
  name: unique-kong-plugins
  metadata:
    argocd.argoproj.io/sync-wave: "1"
  autoSync: false
  source:
    repoURL: https://unique-ag.github.io/helm-charts
    chart: kong-plugins
    targetRevision: 1.0.2
    helm:
      releaseName: unique-kong-plugins