spec:
  name: unique-kong-plugins
  metadata:
    argocd.argoproj.io/sync-wave: "1"
  autoSync: false
  source:
    repoURL: oci://ghcr.io/unique-ag/helm-charts/kong-plugins
    path: .
    targetRevision: 2.4.0
    helm:
      releaseName: unique-kong-plugins