spec:
  name: speech
  rolloutGroup: specialist
  autoSync: false
  destination:
    namespace: unique
  source:
    repoURL: oci://harbor.unique.svc.cluster.local/library/helm/speech
    targetRevision: sha256:5adbe193d85e03d1f1b784add1edc515745d086703c75bc5a310c368c83bb5ab
    path: .
    helm:
      passCredentials: true
      releaseName: speech
      valuesObject:
        global:
          image:
            registry: harbor.localhost
            pullSecrets:
              - name: harbor-pull-secret
        image:
          repository: library/images/speech
          useDigest: false
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/postgres/ca.crt
          UNIQUE_INSTALLATION_ID: __UNIQUE_INSTALLATION_ID__
          ZITADEL_ISSUER: http://id.localhost
          ZITADEL_PROJECT_ID: "__ZITADEL_PROJECT_ID__"
        volumes:
          - name: postgres-ca
            secret:
              secretName: postgres-ca
              items:
                - key: ca.crt
                  path: ca.crt
        volumeMounts:
          - name: postgres-ca
            mountPath: /etc/ssl/postgres/ca.crt
            subPath: ca.crt
            readOnly: true
        routes:
          gateway:
            name: unique
            namespace: unique
          hostname: api.localhost
        postgresql:
          connection:
            host: postgres-rw.unique.svc.cluster.local
            port: 5432
        redis:
          connection:
            host: redis-master.unique.svc.cluster.local
            port: 6379
        rabbitmq:
          connection:
            host: rabbitmq.unique.svc.cluster.local
        objectStorage:
          endpoint: http://rustfs-svc.unique.svc.cluster.local:9000
          region: us-east-1
        litellm:
          enabled: true
          connection:
            host: litellm.unique.svc.cluster.local
            port: 4000
        namespaceOverride: unique
