# This app is used to install the CRDs various system components depend on
spec:
  name: kube-prometheus-stack-crds
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "0"
  autoSync: false
  syncOptions:
    - Replace=true
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 70.4.2
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          crds:
            enabled: true
          alertmanager:
            enabled: false
          defaultRules:
            create: false
          grafana:
            enabled: false
          kubeApiServer:
            enabled: false
          kubelet:
            enabled: false
          kubeControllerManager:
            enabled: false
          kubeScheduler:
            enabled: false
          kubeProxy:
            enabled: false
          coreDns:
            enabled: false
          kubeEtcd:
            enabled: false
          kubeStateMetrics:
            enabled: false
          nodeExporter:
            enabled: false
          prometheusOperator:
            enabled: false
          prometheus:
            enabled: false
          
          
          
