---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-ingestion-worker-chat-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgBtS22aAGZM0DOsrhLUYyCEGjNm32ZJN3O0cndMEW+JLRZ9yhsUqAhpLvfxlCXqdHBUuIi9hMlByXFmLS7NbWWFieQABSMz5MlP8y9oiWJ9fE2HxReN445WHLKOKn/1eDiy//b+t9wXU+PjGTuzoQq6OB+EW5Dm8Shy3a81ONAuXblaFCUs81E0ypJxJewngx4T86IOBvM4I35j6WqEz+bPRggvzi7R+JcJBCz0Cs3uylY1100/NTEcJKgp3TXF26gDu4QR7zaKtL3ZM887ON46N+bp4cLV8TxOFP5d/hMPdpdbu7DizCn/bZFI81G/XHwI9QuP/2zOmY+Xg+TmTQRUeLiqv8k88cfN/qUVOwBFN3ebz+3MEnIdYwDGTjKOYZKUG92LQNtYskKR++o7ZWRrgDVS1gQ3H0oXxSliprHXQW23qCTZWrUTZf7UdeQkay88J4mDhSkhearib5Umkz8Wt3rrkgRHPHW530Q2cxqoG39q9UL2muQo2msWm5j7QB+IcBGafsXf5tfdBc1x3G8AA/Kn6gOWigTqpYbYRgxABk85SddLw4SExcSqQkVHXvnc7iBROl16c1ruhs5dnmYEPUbcxtj0ZLFHI0uXd+T4+P3biT4QjTMJjiGtpSTvlcMmAtGXJ7SbhgYcMCl1BQPFZkaYTP/MNuspr0DPCos++sD8FRkOvCtkscaPN8K5IEM=
  template:
    metadata:
      name: node-ingestion-worker-chat-secrets
      namespace: unique
    type: Opaque
