---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-ingestion-worker-chat-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgBUAxzVrnkpdtvHjs+7DRcSf4oD6xSLtOPL0KNkFKDSH35YNIIODojWn0IDc1UCx/CUKOh0LsZgyqaG9FozJIgsOEQvL0hlOZ8tkx4d+8536DOHxFI9+9XJKfSXGYJdbAZwI8ubZenqtfQY6tfRvq3AAN0vbs5GY67DuYvnuFTijajlXYWmAjCphc97kmmpSuNbAoBskJ625zGRq5C/4+SXSqyRjsBCBitCljMP3ogB6Cbow7qyCH+I/nozqTsBJAnKUog1V26DVcEo/sBqfeSQpA0bRjqVIMS+slJHiIJCB2L8KVWO3SJQXYcByLuK+Kbz3UMCyya8mANvFSebyXMNc7+qnxuWWJcewOE07qLUToljNKn78sO9Xsk38AAGSLT2VOrjsTtbRFeFCzI4GEWv+8174pf33mLUiJlF/dri4/2vrhjsZ4iZ4gQ2MzWWS1sFSv70l3UddMX+Od77A986puDfm8VoyF1g2Jz2G/I8GiQAKSJ97kEmX9gWmV7TysDerbRQ+45KlMusXiZrfQPZy2AI2nsYgCU8WUg5hedDEJuKzwX70UrtX9ABCCFszRdOP7ugcNzPMKY+uiY0lDpVKnqm4/KhzQt5GykBmbub35J8c25WJEl1HXbSRDankSHZDfIZYGeR1eYpJSvp5wI5nzVFoIBQm6IDu318LYlGLmpf4F/F+aA4dYH/WJPCH34=
  template:
    metadata:
      name: node-ingestion-worker-chat-secrets
      namespace: unique
    type: Opaque
