---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: configuration-backend-secrets
  namespace: unique
spec:
  encryptedData:
    DATABASE_URL: AgCx7XLd2tyjkpTXsyKdzxBqHN1SxwkJC8SPhVYAR36MQLBYP2NzuwaVmlsUe6OjMdG9hIVzoKypBlQxdM9yfA88F45oOH3sahNrVENCfIoKvvKmTcbHWWxY+NolDGq6iggMPNNAQ9DD7IFrSvsGaLW+eKe9V7LslNSxD270B8Z/TLVi9+sWCA716MHK1gHxTWiGeFD0zoY5V28aUfJFxOyGZcTiZKO1MhDGr6MQs9lXxlubxXpoG0LxCvPXo/2Laz99LnHz/xE//Fa95np8p59C3OK78zvTH0Qjf1yWjYXuKXuq2NG2P+uf6VN1ClflwZaNAbwtCzA9/vXsYwb3yui7TQ5muHM+eajK8r9+c8s5upGMcOFEcj1P3NZ/FYZBQd3UW+rOrIKQiz66TDkYkRqpXbpXq1Jo/b/OPiSncEA/WyL4+MGzFVnYc7H2Sd295zIlc9PROpmdgEtH//7UGUW1R/tx+VYJZSPnB0xxcIj4BzAfn+KPJPjtNCdZRWLJXeFEK3+a2bjsR7h0qJ3P8bJk2GwjR9PMh1p9tkkyzMOrs9cBTJqmMb1vTTxTMiWkjtwXH9fSundTtqi/6oEpNdQcbYhoUYzv2CnHgITbVeEhlp+HFHd+5ORtS54MabJUfXG8CZkBTIWOiEb1gWFvjGVCkUWJBmu/+5SEf7PuocuTh+f0YjJqzIcLMuf4E77jFW8=
  template:
    metadata:
      name: configuration-backend-secrets
      namespace: unique
    type: Opaque
