---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: configuration-backend-secrets
  namespace: unique
spec:
  encryptedData:
    DATABASE_URL: AgA0tpCy8og+J/K1ddpbzAkX/wg982E+/ye5YgWKbzm1aZZQMjiUyi3LV9i1LKdHt8H689U/j0cFr243OiKnAXWvryNi7Xi4hh0GEbCDjZ/EHekdvjTqxx3+vUtrcMP6+gv+X9nQdYqmKpGx5neMWVcy4/U0w4+dJT0PQdRHgIV8Z5lLfoYchhoHcdrilrQEiQziM5GntIF8Tcl7PkW09JgJ/gfWfrcTJ6KHHCxcyplLTbgn9TB2ARnpJoBEjhywNhLiySshh9vjXiZnQfNw6VDFuamHrL2n50dzGLPquEkvVYA4T1uXpVf3aXgpaV91InxYAayKfv/TNc4YLDkchoptC4xia1JwVvvd3v0VNBEE36eh0Ji4M2oSto4BryG4rgXVQT405AZRDMRODjeYFyAiHe9vKrUQnALL5ozanwLsLdat1qZUnvQBbcAgP5ZIZlCzG5L90JvkTFHQXNe9a2Bakvt9zNOiHcsX18PtT/ewEdqfKqgu0GTTgQzRtMGz7k++QQ7XxAy5H5jGGuJxzW4ESh82wegL2q/IgwnQ1SEdZnql76R/ZFIdLRPbnZ28WOHqPstL9J2jEr0rYGTDmr/ykXahGlcVBRGlFfG2w4udZBEUOtDeJwJEq22HPVhKfL0Sk/qet856GnDRZCPn3bfsM82ynVsnZbU9uJ8nCSseao2j1GCWD90dl56x8p6LJk0=
  template:
    metadata:
      name: configuration-backend-secrets
      namespace: unique
    type: Opaque
