---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-webhook-worker
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgAXF/YaEM3JzraKq14eFWbtCldE08TepnwAr5T6D0MbGY+6oyNASzTFXywpNNNuiDaxI6d2pF4seKHOx+5B/4tkTmjjn2TSUV3TNNLdFGbrlzQ6e0Hhaq7hdh7o/CvhOamSfLTqqgGbVD3h7FT8PfsVGmKYpF/tHMD4K9V/hg0HtHWSndNeExg3HNZzQKuonYK70QuCBpkEvZji10D+U7X4Va40TGiT4rRASxoispwVwbZUkHM/YVlW25rje74WIXChuDp7oJJXfu6ZQ+WJHhoXG6pDFrQQ1b64IFhZAL+pvr6EOOWvb5QNqP2/3+LLuIGmJ2spw9PrjPt9Dq1C1NPnwuP8dO5wOknlx+/JWWkrSmAkLWDV6SogitrJWviMr/ZQFdkmvIcBlbRegD4KggLbyz6MD+Rs0qGy8YHd19YC+oAZucC8NTYWlG8cUEmPbjYpzOBd73S3ylNeJEa+PMwWzPMq55obm1S+BJoLlpRdhH6iA/5UlmQSGaNw1hQ6St4stywSlpb4r8xJ/0JSst6YOBct33nB6NpNSg5w3RwnSKVh2a+dFuwyS4PYOqdrcgz+qngA9NBCORj/o2aZKGnvrwEtBfr+iDnRYTIktebn/3VyYFzYIqZhOcb70vHInkXUIZh4hLoQO+n0Ewfbgb0JuZnePO8FSUK2ympuOlgyhBsEkZ+WRZthdLpnvJERYdrVtbF5/xLTatNKsUE6W1Fknc2LlLaZKcYSyPMWB9lOah6GokyWvdI5aVo/dYIdeRIezT4B4sG6ZehZmGp9w5Sis+Xl
  template:
    metadata:
      name: service-webhook-worker
      namespace: unique
    type: Opaque
