---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-webhook-worker
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgC+AO5WX60N2pCODdQG4e+IFI2wTWt/3uOMX+o1o+NIFe686ssTIihkbU0Jbwy2td4sS5izA9bUjJ95/u0gD3ZVu+QDELJqPK1IZOjCxrIdt8cAYUKZngGoMh/l2CblNS2EFVqgORcyIVsLiyjaaU2jKBXusDB7BWEZTDGlI6a1e7E+kzIsWqX7w8vtgPnY3CIGSh4cniQnUjgQflyPo9YtKffo6IHVn3xY6kIMd393wmc0S7u6SzTWjQdCnI91Tp/cgl3NrFu6/50scrgMhrr95rO81tbXfQ1yQxNEuZdxFxAMYOHqN9usUNQHFxojvG7y6qoqnaACFGeBLJLwOBJ7SaqlVDAGwQ0f3VR5PCycsCxFuXm7W+RjUuLW59RH+aWO64GWQbQMpMjSu9FkDEPxHLboEVQ3d39zTnaaBdnBezZMITIuMqFq/uOzg+dSEDxTmbjoqU2/0AzkQk+zhzLAmnKlcemEXSuFlqIdJVek2XSe+VIEfhz5G9CPCJAmukf/Fuyfi1hfk6UljZ26TnsD/z+b+N9nGzCnChxzLpvqXuutmwg+1QblqcCENMpezgtLg4puN69Y8GsTmzs5u5ZW1oLdL3NrXG/CGgg31BQLzKMrCvGt5NdaHzpXUF6U5CAKuuS5Iey0ec0DjYz5csI2dudhreg9Mh52WcNBmcN5u7DPxX9ZDDqPZu9q4DKFawZHV010AsrkC1ytkBWvtkUxZV1ykMbz6lfUIpgr2zWB2ZZGrsT+EcwBwWqTwsa65ygD4V3LvTkmnikEi9feoGm0MDAF
  template:
    metadata:
      name: service-webhook-worker
      namespace: unique
    type: Opaque
