---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-webhook-worker
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgCrc2aiy6rlOjSoU6vj/f4YGwSWU59CWRdBvhhhZfcnsqTE6VrLHLzALihvEagWKHZ7WBZ9AA1GyyxEu+olYzFO6Y1/0MgIcn7APsn5Jjv2hGNGeNPlKV5kmxSL6+48Atzlx6yNXtuSCS+K8kRuJC6iqW8sjgTHvp8ItQ5VUWinUba/iWiEqO1jujaHkr2kNAOp6hNSKj97T00gXZHzDnbprg1rciL1krHGIDrcCrzoKYXcsI2FgTfzRh3ckIkxblUi3v1BI4JL+5OkLmGuTNsjy7QlDfMphonW7rh0I7BMfX26bA4ib14OIraOqnHyGfNlcmCSDLO3O3NVCnedZveTUx+ezuLtiIFVpRl6+JOrXjj7x4rbbNDXcGV/16pkzb/hFuw/S8qMfmBlzRVfl3kdNQDsXAiLBk9fJPWpUnrDp25Vlj1TY0Ys3H54A238eobCeJOVkGD/4wyjUblyVkiO7wtX+7F9S7FFAQJhpjdMV0FlUNU9lMYSY0ebM03/5W5HUul4Hwjz5fCRmyrB4+dcIqMZ1LSn/aRLWIC6xT/9y97o3bP0u363PsPWpvVEXo4QpAaMQsdKJdgdSxcHCrT6p9Ac4rzrhCGCPbSO6kaZxMZewfhus4RD5GonE/sI3mFyLFDW57hKVoH4t/pZg3jnnSUZ2YsPcXzscHeDZJ/wbDsAkg+KfgekEA/9pXQXAWmjqDGHIgZgTLaOfK67zCrNIz5LYhgT344G2EAEcIDp51pgyqqTK9zmhSZKD7M4ZXv1k5JbtaD5UxXflbH+ZKC124wT
  template:
    metadata:
      name: service-webhook-worker
      namespace: unique
    type: Opaque
