---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-secret-config
  namespace: unique
spec:
  encryptedData:
    config-yaml: AgDGeqvgx6HI657Nv2z4+yNpxAPQn4bKs9GY900BXTMMsn5GvddS+pbd+Z6ttlRXtRL283ZQipM5J6jc2VHd0mb1jiXSg8aID2K7MdB2gmNNoDws3FKRLl1dLCfWpkQPLv0T3+ljUG4o7/ox/a9oaFqLgftOkkgVVLauyGHCqUi3nfJuKWUg6dISPWhmQqQP+HIymRe9r8DIk7VtIqwb9EeiBhg9wh674DkCVZtob/eWuyVHEbkijeUgb6s4cqBMplb8zJcopaLnPqjzdlhC2KXo3fzyVIFPMw7xDjsTyOTvvJflMVel8zuthaUSBO0oYDLvFURjuNa7bEY+gjlq3CIf3PLAcnD9wlcC5efxUuy+vSeDPwNTQXTifVoGy+5Ch6WhSBi6DtlLwxHTLlKqhidXeXeNxZZMbstrvsaAHo8UN4b2g36ySmu59B+dPB4Ez2m/0igVI2KHMgGGHC+HPvRlIo8z1W2r46Vopd040Uf0D6CtnfLFFnYeYBaIOFCT8NyH4Z6JI9mfPqaUxCuzRiL4TDl3UoRR2QPxuiw8UgzRtO8/MyvE6tT7W4MGkWRDPca+CgkdxbLS+b1aqZVhdB7giS99NA0ZZWODFX6ynAPqhP6PHrDuHiuiUyia96ooND9KhVMNCA05TkDkp3a8+4+A8hXF2VTYX/unBefAF5Nl4MJeUIodKtY/fW82aAJ01s4v5jz8gpJEB3cJC5ZFo4SHkkhloG8x7GM2gmuYjYek/k8odogVS7EfOvolqE4LTq5FiDc2iw+tim1IrXAHBDnu+iHLDgPRWRwVyM2Ehliy0Gj+bsf3cum8EkU6jmTTnneOxrY9kQBetp8MMy6V3XjquG6FrNO6LRrbp+lNHbCZ94YTH4qGtiHWtZLDUTCKsr2RR9DIdT8f/+5AElphmWJAJxRqsSAf+ayJC8taKZgh9rHs59XBqb7TmbnoaPcuNtfkNf04Fa4zvbm23o7Suq3FWKN57idoZ/zyxELGZg1Xm+Xm/ox4SGpttSIRgoWB4civNvEKVDl4wbyaAo5MRBAg0gZXSPSwv+akhL0T7qr/5/iXJaTiEBcdZndH0Xl58TQUoF4mT/dTXUDZLjU=
  template:
    metadata:
      name: zitadel-secret-config
      namespace: unique
    type: Opaque
