---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zitadel-secret-config
  namespace: unique
spec:
  encryptedData:
    config-yaml: AgAR1HcugBx1wxvb0bFtL9StbxJHv7OYs6vL22qoa4YRImB4MR2iitVtZyMvVQHR7+A/ns0/tSFs9V6sTcsGNYN9EEkW+fUo/OVvyHknDPs44wTNLBC1YjT5LDvjGeJfiaZlHYND8qZeDQBqJLpGv0bv3f79ixZRM7n0XlQXkBMUOOM+pZLX59eVlwj0Trm7G4hMJ8arO7gEV42KedBKJZeHplSCLf4dv2Oif5atxtvdL907xUjYleSnd6O3CvTgb4V2p+u2b6PkwfjcZ5CWecndtjDIzy9Ncv6k11BQybgFWx9TnPZWIYPbO+g35aX85jLzMz4UOYizm4nskVhyw2qc+Ye+B4nulQTGn04S5M/5XzMR2ucoStnAFUuQUxDfCxGx/PGkAZLNMV/+8oaPa9fJ+OyLQlLhozVI3RFahnsmYv1USWaWIsM9R5KYln2EFBf9+zIuqi97PpMcwzWf6GGMvyNaCaZEk9Hq1xVTs7LyLBJhoeVO211wfLcGhOEakGccJ313BpOAdEdKqAy8882DVlUzvI3discgl5d+7uRNQPrNoL55UaopRHb3JyRi+Q6EkIMB92xc/F3lDewX8eHHxP7x4dkK3PUh4DrogDklcKSrBEkK1Z3wtgnidzctVok9gkFD2DiLOqZTkD+oXFLEB3A14yXQm2ClgBcPFykmOTn1klymvTE74OyuMC7vjLcJXTpSN8JQdoH88TFeFYmObUdIW45xZVI4abQOASY9mYxZc8ti/AQxz7mUVeMoEUgvp+BMEaleEuycCuH8ntvqmZw4EJI0yvcK5H/YZqeonJBJAhdRhoFNNc/pucridA24iT1a8vDzUJDSoSamRZ1E7ZCJzByzO/E09iRnHqPasM3MIjwt1jtUdHSqosaIn6i75YNvDp6qjulGSeOhspzlwDz4fXTgrsE+AE9Z7mX1VJ58jnpFnGWWS2sxizfnRd6ORXIQemGa+m+rfLL5C++CgUXHZg8ap9W8C1J2HcDEspIPt8V3vFNVl4Qi8SRq1z6MvSif/OBV7eU2MOm0n8OA16qQ8MXNiz9wioiYfbhHvYD/h/awN/sYPz37glR8lj7YLodQxnuSPyc6XoU=
  template:
    metadata:
      creationTimestamp: null
      name: zitadel-secret-config
      namespace: unique
    type: Opaque
