---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-masterkey-secret
  namespace: unique
spec:
  encryptedData:
    masterkey: AgCX4ByFWoBiz/NV/4PWLApwEaJZP5dSLMg4XooX97KZbsV5XanfekN3ODMlzP8zhDtktj9spMZ9TH1abNDJDW0uRgsJxl66Bgsh//3lzvcGV695wFrI2Epy7aB7VkRCOciioKp/7F39YICdj0r0YcRgwObwzMAk3K1vcV8OK0SDHXCSOWKHqV3yPBTszuXHZb5VGeaOfzZC59jJ8lLSFImw+mqIxnnYTDTTtCl6cRhAnQ0fhWsm9HxZ/Q4nzIKrd2eEwrd4MhTtJH5jum0Cvk1smUxsOPljRyfk8WzJv6PkSsyZp8f3WPARxCTe48nVM7FAyOpj+BcKjPKfbUE1WiPZ0xls6p7eZr/Alf/Kkws6ynaNSSdXf0n8uqy3ON49u6VLHFX1MH4rhh2zEXr2vbTDas4L32F0LR+hUlDNivbwPNA5Hl1Dj/jlvPm+N5dV63FhVeYdMhjvU7QvjEsPZnx5l5MqX2rGYAO1ZoJKD8lC78/acep3+aigQR8+IreKQSBrK30n8yHrV5d5E6CALIr1ILCtNOrHs4t3Sni7qlfYbnz5MnzhadkZgc6A4SI/OjokoEmPE06/epkMNfno9yI8cKX7BrVkEjYMLaC6zyl20CBkBqA/360e524RTTDSLRXnjtp2MVwDvb+Hyfqb33M/ewYyOiFhlBBm3p7ZjOAB2iH4/rKE8DQmVUBICUhSTp53ro2Slz0eZaL9V13USUkg90lQH2m/lPAhKveBCANz2w==
  template:
    metadata:
      name: zitadel-masterkey-secret
      namespace: unique
    type: Opaque
