spec:
  name: unique-service-app-repository
  autoSync: false
  sources:
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: HEAD
      path: "2-applications/services/app-repo"
      directory:
        recurse: true
        include: '*.yaml'
        exclude: '{app.yaml}'
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: HEAD
      path: "helm/backend-service"
      helm:
        releaseName: service-app-repository
        valuesObject:
          nameOverride: service-app-repository
          image:
            repository: harbor.ingress.pcai0201.fr2.hpecolo.net/library/app-repository
            tag: "2025.17-1c5de"
          env:
            LOG_LEVEL: info
            MAX_HEAP_MB: 1400
            CORS_ALLOWED_ORIGINS: '[]' # Not required. Kong handles CORS.
            ZITADEL_PROJECT_ID: 'null' # Not required any more, as Kong extracts roles from JWT
          secretFrom:
            name: service-app-repository
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              memory: 2Gi
          hooks:
            migration:
              enabled: true
              command: |
                cd /node/dist/apps/node-app-repository; npx prisma migrate deploy
          probes:
            livenessProbe:
              httpGet:
                path: /health
                port: http
            readinessProbe:
              httpGet:
                path: /health
                port: http
          httproute:
            enabled: true
            hostnames:
              - api.ingress.pcai0201.fr2.hpecolo.net
            gatewayName: unique
            gatewayNamespace: unique
            annotations:
              konghq.com/strip-path: "true"
              konghq.com/plugins: unique-jwt-auth
            rules:
              - matches:
                  - path:
                      type: PathPrefix
                      value: /apps
