---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-password-secret
  namespace: unique
spec:
  encryptedData:
    rootPassword: AgCqcF2IQZP06vRa4yrNpfooOAyN8bTv0HbjamRI3ZLx7bMzH75Ph9QHO/++U9QkF0iI3+AGBEr8gqqJMsNS+8WOkAuOkz7n6+qZLo3buSaLIZw+9xMKnSkaYi2molFA6IDfb2Vuw65qfoh7rq50I4GOhzsc86AfJodPOsoG3KNYW3PYaUVKilWnHuEnFmSxnutyTzfGZ1boGAPro1g7SiUOg4do2m184QkK7XyPgvOb0VhQN2aHvA81oHeFO7rvJDqvExsDHPCdr4Hm6q0J4rDIMLYmBMK89wwg8lYlMFdmz2cODwgdVTtUKJG9F3vfl6PxwKPDu+d+jsYXduedKBL/Y85RffwWgUzmAiigtZ3evGssiYRpN76qWMoaKkL3/pKfHYC/erAWZF9Oib2r0Sj/fZNUAVbzHWbk4/IG6rElonP76tRbPJcu4le/j54yIJi028b/kWeMVxrrVikcQ8aYkYrVQ1E0PlEdnOvdytJNIgQjwrDI4L1hUkV+yfEN0VWMscGqpNlGIe9GRvwWEQXdZmZ2CQfM8w3YBXoPIQTTTZHOD9vvp/Kyo9+1WZj9rGpAyiIEFiMixlY1bm3zM5kbvRRlYgt08rpN2FMOMkrUiGipPcQxwo1qmGlKmusOWKDOnYow5BIKoDtKvJUq7ZuyGiaJ/8UlMebdt/l6XE7omPF9iOIFmbW97JNb8qYx/fl/9Rhr8sBNvctwz9PTBvqrvyHSv3HrKke1B7OkCZa7gQ==
    rootUser: AgAix4RpMTxaFu8OG7o5j2wqTedwpxHStKP+LR64P3zNtinHUa9NqYgeSn05AdbrCg6GNzQw/p7zpc8OxZ6B8flEydumD7QSJSSrlrcRyoFsYcVnIzKtT0U8JYyAB4OgwiWb99Wb6pyPWdR8vrYPVZISgzm9fKSFQKvLIZBCaem63ZgPbhmYepOcD0aQmsDzbMBeT/5RXI/JQEoBtoRYJH0QtR/LhjY/GPDP+BmwnoZWRY/5LWvCl0y6tgrSkVsjLuG70MhlSox/80/oqNbajTR4+WEa7S09kgWUGOj1aiHQmQzLp8iUoNIjB58WDO/uXuqwIfHTu67KZmdYrRscwxV/n8CrstdEvCMaQUlDz2+gizoizhwSqty2zCvKMpGYKs+kju8LykRIKicAA4wtzDRIk5mF2S+hkiMNXuhHRomf+qa8orJPbOGURhR3yzIdK39qF+NIe5wjNMMkqZZFAArvciqVXneK080He8P2TUwc6q7inDAnuuADwPnXIgno/ynAxOo7S2ECojPEzQg+YKM+HwmA1ArLyrud71FhsGxdWiuLuILGQF0iQNMLuviWx01mBMisr1k6ECeYPXldyQ6JCejsrJyk1+zVxX8T4P1xF35mFx8IO8uV0mBB+ODdDDkBDJaUffazhsPuMt9J1+8XspWst/dSVi+o+DJRITEcxb1loRIYMZeXWRdrTCTpFSdNgnlcWw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-password-secret
      namespace: unique
    type: Opaque
