---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-ingestion-secrets
  namespace: unique
spec:
  encryptedData:
    AZURE_OPENAI_API_KEY: AgB2ockZLT7QsUDouIJzIJmH3lgAdiBZS11k5omjQCZ+zb89obxs9UJS7TZOk1P83iYsukEV4o7mPbNCCugxovEisyY8Ryod06rhlnMVN/+HVnGdnPMw/xn99L+ZD32ArSWIA+1cdOU1sjeMk7bZ4HumsIRt916EZ2o5reAKPycpx/GZU9b6NVSOdHDhXVeo0nwXXb3LIXUD50QvNpq/0JU8cIAuib8RkygMr43IPehmuCJCdrbf1lyM0wj6Co00NGfhK4tQARl1Hq4isesiCqlMo93Guxis89R+WCLNNkx1MnwvKJgEyTyTmqYiu2Hgkb33jlxQDHFAKGfWe5CEMgmfCxFAh0vrdKgkF5ca+qlSoOsppWxmx/LA95qznuwQCKOdXsTppkNNLY0DdUgeN7WYbTWKv3lXR8v37xVugVVY5pdXzfyxVW8l9g4XBYCj9vHUxFkD5sTVLCOXrb9aiaI16wYY41LUknbqGRJBjSEePhoFyx5QRwGfM0n3oLFJWVqigZMb6l+WCaPP94Ym9XnHY95zpHdmqjnuDMcpytttAhFlKb9LHIPK7IELjvaMreyjnnI1aV88opl0ehGc440v9iSy+NPHPX92q+gNNo2Vxy2cGYEo6J4WPYrwOhY9I3yoWT0CAsiS6kOA3r+uLFd4pOF+0Bclh5OUhhOTBzUxr0U/W/TTrqLnCFYVOTfd+PI=
    INGESTION_ENCRYPTION_KEY: AgAQspocqO0LMNFG9zkPrjavjNEs6BQ+Xb9hXSlXsAMGio252cP/PDDSswZkcI0lIYY9NlM3ofwiYvHzTEr14hDFqgBB8iUE1JlkCw3k5m3EPzb1tYnUBXTC0IqLltyvzY6HxHAWho1S8AkBF0mFsXCe4IpkRVVAwhplhM/g8sKXUb1eyPzWoZjFMCwX1SAYe1jA4PLQyDeKOAa99Lme9zbRsrYOJGT2zj3oQ1SqQuNHYTa+Ue9jwrpmvdfGa4+uLevQ+ql+faNaBT6EX1gpz3oHMp6qOuKN4EbCuX4YKTcagByZ/R0A2k8Z4XEqmQ2BqXPix+Wclx9TpGqa3ffyjF+xgCOjRE+WtK0XBUlpX7LXc86L5f2rRoT2e+cTS0d7SyUe9yUDcnzYgXd9eu+bTb+c1j8iLpOPJu+2JwDhQWyFouhVNYcKaDKn+s7PrhLalmi6AXTLVjiMivxw2Wv/HZ7eGeFJTgDypCwqMcFQXLPazZhWDA4x87j0o/asysFsTeMt3xfta71Tmof615ll90KWU3lh8ShOW3cciTwS2k9h5/V0yvGmKulgvaDV7aEaYfwZsqUg1d//VXDi8rT2kxVsY067q/3QAXCN8/kddN59CGadoHMxwGusUjXgVi/Lv3w5c/+5agQQoEf+Vvh1U3DaFc6iowwC9ebZxryP8VoXsXqsur2UwYYqCsASR4INypYae8ySi8THDxU2s1Y6E1SoAta3NaiOOX1EvaK0JG27UIHvjjrQOfmUlMC4T5R/gOMj6GtGgUF6K079vuWjNNGe
  template:
    metadata:
      name: node-ingestion-secrets
      namespace: unique
    type: Opaque
