---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-ingestion-secrets
  namespace: unique
spec:
  encryptedData:
    AZURE_OPENAI_API_KEY: AgDTrKEC29bYVms/NEQH8r8E8dfAZLbjPt6sPCsaO0BpNaXKOq2tI7xo/bkceyga15ATAM387KSDvwYmtoOTLO3D5bzzzo9mJkZdk/zXI2cEProMI0p+7AFjbCvxQjL1PBsksIEyWNqTjxfy84leTRfn5TOdbnV/tApXFizgZZrdS8wmfGdNOBdYst82GisSaPc1PLcVFYkLCAb/KESsoY2YmcvJHKyATAng0ghuAHVkgoBBdVPwpZJLDbcEGuuF+ZMdgqffyQB2VF6uRo6R72kbEiHWLiUdtWsFy5gp+qBE3hlVPwNM9yIH+SGLfSNY+6D3wvkt6kkOXqEhQU64JY+ZNGnZ6j2nJpaqNIxRutI70tpUSSasK3Epfbgkn/pp3NDaCvLe8yVrxlyRiFxB0Xi3TOaAa7r50p1+0jE0DQM39k8MBOJbNkXMfYbc0XKP8ZaMotfSXBe5cTx5KMzazykxdDJPZTnV4bQpSqrxWqQKvjnICWQYBW3FYdYikgs2FqnHxwzOGnvWXS4mhycqqE02VPUD8Qw+7ZZkHbScqHPQWXhlfyW1EMBe/yZgWsKA7qs5eJbb0Gxc5mbEyNRzOHtYylGT7HkvEBSoukmlooBmcrvz6ekofSICCv1nQHlFzAz6selWVVPde22lJ1dpD6rSUuqTmTOYfmlpU/6otqMirRjF+AodS7C4yYrNBD3cKhQ=
    INGESTION_ENCRYPTION_KEY: AgC2TlLOJoL0LpKOWW5vdWm6mDwqesTANQBWXWmtr7TTtv9B0vuB24ixxFg0VDKSGjUQCh/JxCx+TliGWkWqV/bSGC5kqtFOssAiS3k9+qFG3dm4Rpr171vaHGXmjn1pe9NRQttRw8HKZM2OcxxKKoxct7QzatHgU7XqYWuKM2OBGB6buY39gtgC+JGSEj1YRKHW8UhPBbuKqxf9nvbSIaBnAbS0dUlJ8SS1p4n3kyihGLFDbp/pbwvJWlFVjSo3mBweEvcSW6RYEDpaktUfc2eaH5saZhFO/Rh93Pb5j3Hy+2MlMLL511IeVDNVCRlez0dfYcOjQoUfjjc/oO8/CQgZwzH32Hk6cfNF1Y5efZ9MV7kyv/TrIqZRe11m2RQiQvjx3SdtcSDpkxfducg3osO+9rn8ufy986v4CPGq0P9JmX+u9+5QvbBu7Jl0gFiF4WqYErDka1BLuNHOs+D2GiMM/sgTfNsCJkK+Cmi4Yq2IEUcYtR/SdRzWDdckRNcgjUirsmBg7hoWjCL1nLpAXV5zkm+Fu8FiA9AXWO3f9WdRWoMTCowp4MBKmyJ3v52aFUkLNO+bW2PEvIn68sc9OqQ04EfwLARNaL5mvOTSWIk2MOqCavzqlYY+ivUhZDMQW7EHwtJkRca1bV/T7BH3xA9cvROYxrGNtenegjkDakGsQ59ZBvJNXwx48tb6A5bgv86Nu2mfeHErBxxXPwxXitBOvoWcvF264XGZp7SICF1Dhugo8ihcgzqOh3/WWKSFmPw/zYf0i+NXCm/pDlOAY1Uq
  template:
    metadata:
      name: node-ingestion-secrets
      namespace: unique
    type: Opaque
