---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-ingestion-secrets
  namespace: unique
spec:
  encryptedData:
    AZURE_OPENAI_API_KEY: AgAaj23ZzpVDRH3URLsc8xg3WG1pQnrXNkj2qY7tWfHSOhf2ER9Qk/F4i+agX4+bRcauhEp8TYvBmpMjbg9RFjciJoUR9OMshATVWX/3QxdgB+oCERUxHqEDXhET2Ch+0ZbHjFKb4WNzlRWvnmPmxPiGKcPbzx8IQkT9+Nfr76RsBvnYcDO+4xrmOWB07rLZzUCdKv7gcAh8Og4n21SIF2pwf4Q6hkXquLi6Wj65bZy+yB4xU/jxbCQHixczWpUwx5KWWUid/H9ccBvyOQ2M5PECkGSIkSPqzfE82fgZ4s53zCNdikqnjq4ZI3pnY687Obm+vU98jgnFRJ2vAbzbCd2kuQkHS09R+IV4GcqDFTL3vF/zv4ieoO50WIeVaMic+4w8NtMZKKmMMzc+7uh8n8LYikyA9EIVBKwifl84tYXa0hvC2KHmDkbgHVns1h17H0C6VnddVGMfBn1AXhsjjBPTQNoC1VFpMoukoy6yQdr8vMxadcoXQBadsmOoG7nWzvWL91jTmFH07To++4cIuCFNtHYi1S8yXX3S2uGrJfyHLaot6xwY20P7FYI3ahpapLsTRujWEB7ItQGjyZKFFRG8wrkRaQXOwnFEdKBGdTCGdcrRm/UKdLj73ZYsKwtxmo8HGnl8iRWROERFWIHaC+/+qwH27LmiXQhwmCvor2rWe+NieNXgv68tQE4Z4r0oZgU=
    INGESTION_ENCRYPTION_KEY: AgAYoccdDkdC4LhcUSlKsOYoPlg24g2Jb9EZKKevLT4RudkghobsJrP8febO4VmbtiQdz2fqP+JEKhsIW4yBoIrsL/wBTaMuSuEGR6MEdu3a4CBgEmO+cPPo+NjOVS7OH9Z4kgtQ5JsT+By62Ui5JFvk5td0cPeAB0xWM7KYtfpJp4EW5NKXIN5BcDr9soYFGDzGuJrtviWD7+2NJES1Ad3I6OmXnNrhFuHUJcQi/nGo8PrBfK4mAqIX01ZQmvdjaY3JrNwS8IjYEi51AH4WX58P22CRzQhehtfF/Cl4NPTgVUaFIR9MxUeiw5QmLlzw2oT3ES5XQtYPptALR+nTIoYvnfV23RQS5DYOIlX8XF8daeQswB1e7TSGj7I+NyRJeKTHpi7NUXmkeIbWlVO++CqUGqShB3tMbMxoLnubUpGsxXX84Gr8E+T89EaNkwNzGj7Wwtixl3/6SWmyFiTAq1vT0C+1Nf/TQfk+HTVgOL8Din6sI1haUpXKTnO3Iy/8bj7Fm1fCFgx/MAcucO/Vq4PUhAUKryC5hBs7Bin5CwxaGmDSQqxphJtWmq+vaSbXVWFGl0jDHvBT+FHX5D2+cfZNQ7hRnxvses0Pig5kRCgtyBqUvDLVPV6qN3+lbAsfe51PEwTlzcKgpyaj29b4U2PhCRxV2PWQKZ9ENafmhhCW7E6WCTxsWgZjA6f2pCAFUMQzFB6sI7wBSXQePJKcqRKIoZsxvakWx0Kwgz55LGnP5Cw9TpcsI8QKOSJAdFOBiEzlvNaSpvWeLEcT8TRbzNm8
  template:
    metadata:
      name: node-ingestion-secrets
      namespace: unique
    type: Opaque
