---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-ingestion-worker
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgBPy1GfuS6i/taqlUBaNsxN6O9vvFgNrRBqkbdeIqfJF26QIDa+LQ6KfPuV1Mmz9bvfTqbQ2O+XzdRuCbB6ja3G6dcZ64ftu+jqQhWi+e9QwP4n44GexZVIwm2fsCZik9FD2VKU9M0/IJluttSzR50te5qD/OXJU0UGQ3raVJSCEUC86fsegHBNloemKfdHeObcAG0jmcwtfM7cBNCuryko6W9P+043pYg8zirlluj1Yw/W/eEZjbjI0+1wchh0RXscPVJ2BXLbESm4OhqdJrZ2qL6iFJnmWhkq1iHbQYeKMt6uJyBgji/3GES9KD3Jz8A7e612EdVMIPm0jOOZqBIXMnPVyF0sTOmGZbi4kcIRJvAGmPjwRewQ6vWTECK28+4tx7lPeE8x/kEgOfkhQsD8Cjt0Hzd2tT/EyjNYYvE8ul65YDevP9gUwRX/hiLsYmifpe+uiJc/zHuSdrcY0OkHapF0boN1LDZkxdZ468jRDVOgzlzZIAzkQi0SCBFuOIuarrXg3JKAjXWCBZYAoNpfS+tbe4L6C+o8z5YzWCa0jTG012qNTG35584Dow4ercsCA/FRzwzHs68ZWAolw9V/uWD4Cg+7oruS42EqXirc67Q+y2TTxBtRRVAZVW1cqPr8jPwA0Fux39XY78Ed6++YXjsp8b/0oqyBODMJu/tJcRROWzleeURb4QDu/wtDoyL/FDlXLjf1W0KU7pfraPFxobSealTQHg82ww/aUS6Hd8momT40d1aza8nCYjjJOhtw/8omIy/zfZ0U9ZGT7P5ZOKNB
  template:
    metadata:
      name: service-ingestion-worker
      namespace: unique
    type: Opaque
