---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-ingestion-worker
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgAmnHleuq9KDZ210sb6Z4aqupAJZ5UwgKa0LivtxlLQMMfu13e0m8yx0e7wLhOnouXyoZWqGEBYzqKbZBxFA8Nh6SVArXEuCYmdOJL1H11W569tc6Ghmyb+RN2aYmM8Q4/nUAlE4fvxXVI4f8saAidqgzPAFNtHkwftwJbxhtVz9t/m/+dqpw9EkSaQI23Fj1CdB2xcAB1tYr0hyc22NtUmY47LJ64DciDjcv4hxyrIm4TJbmuc1PmpvO3RESx7Fi/L3JPr2SjITHqfFIAZnpjjAzWuMhSm8ubehlI3JwtkJhgxlYh2z7bXk+EenUcx5+6siGiJ06+ODIpTdYtDQeTT3cGNWzGSvKHrqXQpJTl60VcsJd55QB3uGbGbUbjnmtKrXlnFB2pnAmiWweRrz/oMtxi3MZ70usaZ1YOpvR8Qy4+EQtD2Tr2GAgwpdIQKznKq4Wn/v3zB9vqQtjQNKpjvfaurxYwfoqKzeOmROoJWwG92ryEctxQaEaBtzFOBZiOQ0IJ9qEgQ+8rSqGdVRqu1SAH3XwlgQKLWoy6kP8m8/kpRz4EsRVfjYSAeQkKTBltIjkmDbSOcLXiVUl3wo/uUixn9EsyKKNxGBZqgnYkbVjDdwSLJS4YtA1iRnUFa++1zCOtOonRN+1v4VIED8GSdWdQxp5qIGuEa9Uz/94/5t4uf4CZiHgiaKwW+5YgWe4qr3cVmM1X0HEvmxh8LhFLEABwoJfmXH35D6huypWmO0FLlT2KRK1xCzYXfXqRAWnoZHV1+xcHNFvxts64T01YWEMG+
  template:
    metadata:
      name: service-ingestion-worker
      namespace: unique
    type: Opaque
