---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-ingestion-worker
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgCaCPErioUAqLByU5AqWzXfwShzkw/8bVt1uEBpNru9i7OTAQB5YHc+LjSkEaqMMmrZpVGwl/e6lsfYl8Ln5aLQN10WUHS0vs9jqMo26PfAk4uMURX1JsNRyezUD+PeHQMvX81ZPgFnm7PGq6+kWqPv02bTQJUXbcLnK9inGVDpgq4r7lpL8QCgUllVNxNronPgvcwWkzZmiQFEhQlHQGazuQbl9R4zt6LFqz3UAMXGevf1s6xxJpLUiniE21Fyoo1iUi3s1D0ubJ+MFHbQx+prJRt6jhq2xB1PgmeVx52Ej7gkWpU2yqUGdQlvwoMJr+S+dSXGk780voOqDJn0mNfonU61Om7lC4Sk/qPcxGv3bIpnyvWsQEKMyz7oPkGt+nohP8HWi/nSNQRMpiO04+QKrMIooRBx9cHiwWGM7KmHo86OSCWPGkG/4kPTlMIjTeumQ6VNtLNH9HtRBkUlW2nnliy9qpgmup8IS+cOH8AMF9M6Uq5QAQabyEFleZivv0c3xCIipziq6XJoNgYNPWAXrtHRK88gKks3X7dplGxSh8+zweJEaupDyc/1zf3IOyRR42OROi8Gye3G75lBBlROvIgzIqda97j8jigfc0WAasJqwshurCHp00uXGuFDBvy9JU9xQIz+e/KHjC4S/84l4jNGA2Uvc+9l4EHZtbsgf8kydcX72vY4jApXgy8kaM1sw2/ShK1Tzx2VJp15KsQB/GhAotIYlehNyGvKbekiSltQ+WVMp0LPjUM723AqgEbgou26X62Geeexuo0gmNejGSAI
  template:
    metadata:
      name: service-ingestion-worker
      namespace: unique
    type: Opaque
