---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: unique
spec:
  encryptedData:
    password: AgCirloras3f56CmrqQzM0vutoA959MHEo99Ot/uy09moGt09oPouRpKTxUVw6n5/n1NhseXiY7VoSgskFF6/xP1hF9iVD/JXK3C8QgamhiBfQS0eJoi5aAukIzcl+/7e2werrJJY68BXTl6zqCBG09eaHcQhiPyZR1PNe2D12NQ1MO5dqLcsoO7xG2JdXF8lrGgF4UrS0j86kAf3yRr2aoAZSp4HXP3NT72dcZClFedaQBAqj9eU0EC/jKcxzTxID2AXYva04CwnKYZYJdL3ZP9sje4eG3OLQmDRxR0ZUn02BUeNwK4INfp+WfdLecPc31Vt26NpkGmjNmMCJVw5EiG+wvW40OQgPnvCIiqBkSC7Z4pFLqD73pJH43PmzNIbnRe4G9Rx7d+5Ov0+Iuwo0oFfTiPVB/wASP/NdVDW6pr6lPaoiSWlH8gqMSjJATdLV4kWtbeH3joK60vCwmwekhHJc+vvHHAwV0XSeITUrbYQ+ahbl8u3aWFZTsNmr2oDsUGrHcobr5WP84COBfFZLm+Ydi3FoI/pQmJ70JMVJ7ko8BQ5bwZN3maN1RaDBda1cSZRS6lEMtnJh5Uru6SKtSNEAv8TELt4PxDHh+OApAdMSqk/cd6VUyehEIqJBkboU7wHOCH9nETDhDorsUy2zMQJc+M+v7XApH6iB00jODBqclTUNs+BhttFsSi/UP2VQmTUtMr7M0oqFDIfNf2FgjYKambmCksEd/sPB4aqHG2fQ==
    username: AgCecBWiU/aC7s6D5tTFT0ITWny86w+TAp8+2EHTk4xXu8LfvrPrq5a1NtPP0xXbo3AQqYTRqSsH42LjtmFrVWdBO1QR/ZtJ3DFpdOq8v6ylItn8DXgD2G/u9XYVnTGkoWHsxveh3KM42huGl8LCBkssVp35xshF0R16aupSyUYqxXebb7BlTdFOotq9bH96PkO3Z6B3yhnrKAlG0+Bhb6/Y5Z1Ilyu5rfvUUDfgnwDmoI9clXtJfZCBNqSmcmtwAlqf4odgJz9ZN4ZeZYiGGZ3O+0vgstE80Lnv8jkZh6NV+swbgHcCEaqSj4X/FvBGMikqIr29BpXygd5f51LzO2MSqTEOfkjOcOjL021U6jxePShuKhc+3na/RdqR4PyithVDuMSn0ntlb2qC5gl0P4TiQw1OAWWvU4BJ2Y05I3EI1tDpkumjfybHRMSdEvfQgxKe3maXpzqhMa2aGMmS4LN6A7Y4/XgfyQzZq6gMOGOl2aoyVdY2kKUi9aOcT+RJ6F4QirOOP0rz4mWABnN3tmA9QbtrrZaWgwjmbN4M4aVftccri2JEMbJyb6feYm8C6x+56LvIZtiOVLCUIhSNhreIPxd70SPdkOp5go2uMSxMCKyqML31U+8jsha9CNmATJXyNZybMSyBvSzEpg7oodXtY+mAI7fMEXcPSoXddgdfhAdR9fGdp07j547dIysLlK2cRuAo1SobnQ==
  template:
    metadata:
      name: postgres-superuser
      namespace: unique
    type: kubernetes.io/basic-auth
