spec:
  name: unique-service-theme
  autoSync: false
  sources:
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: HEAD
      path: "2-applications/services/theme"
      directory:
        recurse: true
        include: '*.yaml'
        exclude: '{app.yaml}'
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: HEAD
      path: "helm/backend-service"
      helm:
        releaseName: service-theme
        valuesObject:
          nameOverride: service-theme
          image:
            repository: harbor.ingress.pcai0201.fr2.hpecolo.net/library/node-theme
            tag: "2025.09-1a6e7"
          env:
            LOG_LEVEL: info
            MAX_HEAP_MB: 2100
            CORS_ALLOWED_ORIGINS: '[]' # Not required any more. Kong handles CORS.
            ZITADEL_PROJECT_ID: 'null' # Not required any more, as Kong extracts roles from JWT
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 3Gi
            limits:
              memory: 3Gi
          hooks:
            migration:
              enabled: true
              command: |
                cd /node/dist/apps/node-theme; npx prisma migrate deploy
          httproute:
            enabled: true
            hostnames:
              - api.ingress.pcai0201.fr2.hpecolo.net
            gatewayName: unique
            gatewayNamespace: unique
            annotations:
              konghq.com/strip-path: "true"
              konghq.com/plugins: unique-jwt-auth
            rules:
              - matches:
                  - path:
                      type: PathPrefix
                      value: /theme             
