---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-theme
  namespace: unique
spec:
  encryptedData:
    DATABASE_URL: AgChNwgDepks/a+yWWzEkpS7yNMT626WNHOgV/+0CAIIptnCFnDOjbOAh8yWQ/HQUmUJmPWdYcvAOXp55UvJ2VfOiDInkor0ceMzrPKzbYEVl4Hy5eKXU75bUqEl031Z7rVL2ujP49ewnL9R4wqeeyDKau3Dmm7SzUDNiq1g/DN65/Awb/Bq/HcHtcDb+P6OA52bWSewkvzevpoUNTxCnzAqOfVOrvpgBNgUAdDBQV/zzdY+hdGjAf8iYe0BC05irwXDCOxO+yCnn6j3IgVOQpcyxzL8xsxn/FgBnRTN1WSiTSmhPcXyT/fT9XHhNeHAKsK6O3XIDYOSJJRL72sdqP/liRiH9MSXVTQUCNk8xnjTeFJ2DpSeat6XFkzY8vHT2kUmF6ePvdcRU8gPc+YXAE9SPz0lHVb3PvQMR9/eaOVLOy+HEdgsL/4R9IAc85FNN43YH9oJuDbnSoxfGitXm3+IevDIqWJvp84cJ9qVdhQqHvAxpZwnbPO+7rZhR8+0E/+EuBJ9U7v2lTgH4AW55Ja+lnjftUZ5TFM4FR6rdptnYMW7P4dE6iiPzaoO4vQkbTLr1zB2WCQwU5RivPZL7rEkTSOPZNl5kX7Ba4SgSzAj3oG4Q9SC9HMu3bTkyEy0MCPo1Pw8DV+MbYVoSGjPSK4fPybo7NGAHnPGltGvhzeMPjjPtB6WmkWTGagt9ZFuh7Jdqqe23fE4DGZkhBbfQ7O/Hdlsg0geJO4jk5ZGQc6RC2rnyTkwsFlspXhAUdlbKWZozocIWgFocBynJVFRTLeBtbR42SoczZCpaCKYh6c7QDNNYwBg+ys5GjiJ+0S2AI3Ws4D4Y2M+MOO0b4w=
  template:
    metadata:
      creationTimestamp: null
      name: service-theme
      namespace: unique
    type: Opaque
