---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-theme
  namespace: unique
spec:
  encryptedData:
    DATABASE_URL: AgAOng6+JUoF98qvMI5ynC1ValNz9dZNW7xGTqWSAg3U7p8igVSran/J+x2Z/f9WDcGPfOF63eSqz1tUTh19WuPARMHoSovGYXTylnBrlqxb8JkgMZxgKTZOtDNiTvKV4H76evDTd3bzjljP0cweElUR3bxjpefPfJwURGNxfLaGpGXqZUasn8Z59uxuKsKJHbe+1q7xEi9fGGd+Xb5ojDLbNZAG1HqoShYAVwi6U3JD6kzM9WQjIxg64nzNlbix+a+Rixo8FOxNbiYkxUtJqCCD2AiyOZjIz/fCP0SM6krlNRb/3TS7777ygS6O2RrTCE85SQkXjLl8eBr1DxhaoYCE0sWBKl8oSRY1zwqgmXCLnPjMCLDgbfcJKha00HspgeWu91N9tHpbaSOxgKWeE6Zao0syoICKEaaNLB+BJcNimRNLFZh4nLV0kuqHS8Ul1M6Z+OxIL32/rsYdb3JqmEnxLN1HzOa6YEhun/9nyM71S6d7w83zOfgKzzqf81k0Ff+Fm4sk34xYY/J1PD+yNZEOOTE2QdnjcAPLf+luYgNn9VNs7ZA9c33jjGxnpN2BjUgcGN47YvH0N7onrD6IcncVeQKH9JYGn/qbdndGU20Usv33Gc2X+JAEuj6RE5ZG3VlV4TyPviJJbaODBRSBsQwEAoK/lB6dpMfkx6AoCWN9OLqjdYzsWw+QBOhumeAtRINV/v8lWlECraTkz3IHtzNpRfIePNh8kDns20+lx4goclYozxKur0/Kep6lbM9oihGDA5hpl2Jp9UR4G6phdLoofPRUY9ASwN/b2gMlzf864mDvUoc0/ohMQSnEjZSSseBo/T277yxCKk+LH/Y=
  template:
    metadata:
      name: service-theme
      namespace: unique
    type: Opaque
