---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-theme
  namespace: unique
spec:
  encryptedData:
    DATABASE_URL: AgAx2w7AvoGsSxRU4uYStJXFzNvFvBD9KS+KcggewdWNS2xotBj63o+jBKNWL5XFJHJeGT081xmbg6QXyvfc4BjGa4noL/7VPREqcZKDIcOKXslj8z0CGPQoAzEadjBiU0NmoPUEvR17Tib59izFKxBS2PERdMlDxQjAqr/+iG237wNu1Jgk6qjxVfvdqRSMk4OuTQPTXfMhEz75MdsDoxpBFHASV64E0zHt7nB0ZdFwCJ2w3gNHpdSOu/5sxPUw2zzol7Mlec1+OWD39xrSpz1f6F1ueLzmXKBgfUwyllVInlV6eay+l3+MAxnhXNgcRnMDwhizAf7qMSgOEgTUHRJgpTaC6FpTnpgqkB7DjC31A2DPzNZoX7jEbRCPm/tak1HKfzlA2jW9PWhsXdOgPbxFmog8atkRD/Vf9vZOzGMl2z9BpczoIK2Fp/tXfp0mbo+Ft2vQN9Z8wHOkZBWFqKju+JdycMDFsZgw+eUaamVr6FzxY7HFCUXZPEjY1w1UKer7JNQtr6PoI5fCbHhkpHUCfdYlSFNEcU2ZpHDBpv5l/WNRDMfxdFeLGLO0b1yakYIV2We8XVJpsFuuwSD7Dr8uChq8otxMlMM8ePWk58yhcj39/dwNX17sbTO+jtrOQxop5c9Nf/M3v7k8rzJcQJNXhJ0ESx08PrPPCXRhX9ZslHUNJUpT/+/1OtV9RbybKIajQpAah35BiHhd8Wu70eWxzQsfepSWJGrHFZPVFFP41Dj6i+NseDJOwpV6q2ypbKrboWjIpQboFovCPzxWwH65PBtKDfuvOQODxpPR32zpSSlty+myvwXepgngJLqiqVE2rril5iLwJNrtvm4=
  template:
    metadata:
      name: service-theme
      namespace: unique
    type: Opaque
