---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-theme
  namespace: unique
spec:
  encryptedData:
    DATABASE_URL: AgBpj7T1zVrWTz4f2ELRVe0+jYnvJwDX/lnXJMuA9oNXeWCGdSSyoZKxyq8X1VH5Retdv1ct+mExDNg0w67mOwUGKdKzhxutt2ZMgA+AJMt/RkLLRQpl518E3w5epGghW+RO4w+5n5RBHjjO2PqrI1TIryjbWJuuWd5fjG7veUMgNWEb/7snMdsxlyP8cpbwCJLQz1pLYbVq9GrSTaT/AmYKyaGDQpFXwCHL8XjaZq66cSsnA9A3EkSaLWfF2NNjpihtNMWoddEsd9qRxiSCROv9FFKnOrQQllapX65g4KwkRFIy/pw1G3hbfF2OE0O7Y5d5irE1LymVn5wKdtU//mdLc1HtYWPHq2cUfpvP1JMkGWreGBd7wEjZ4gt43M1Ad/WXlD4QR/gDOfBNxbrx1v2/SkdwM+DG7u5JAb0sIVIqdYQDCUil9Yr6Ub0pn9zTjslyXanQcjsV3k5dzGUb8bdeMH4J8H8FqKw5lzoz1BtfR7bpGyDUF7FEFyjfPPQxC+THNLOAtP8CM9PVlDND+Mo20b0BOiVjeG/CU0uN5jmchf+y/HImXF5vyrwKDP+QG5gYWa3hjL57sYJWH8+M0mBZtb+IuGKj3xu/RhZXCz2HE3RANSIIXLv7/UHHW9RxpjnRb2chBbw1e50NONcNweA4a5ggBkA1eYa8eqWCCZWjwOc4i6W15TOrL1TkKcKlt5a5wAwS155DSWf3SNRTSWvl9DYB6r+rsLLySMovoUu2dze9Z0jjGE77FbAWtMLmvrTTwcGKt1aSz/nJx1/KdGl+oxiwgy7lkB5eb612xOmfzoSTbBD06WhM8F7/ZJKt7nJG73pRiLV3fMoPn0w=
  template:
    metadata:
      name: service-theme
      namespace: unique
    type: Opaque
