spec:
  name: cloudnative-pg
  metadata:
    argocd.argoproj.io/sync-wave: "1"
  autoSync: false
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.29.0
    helm:
      releaseName: cloudnative-pg
      valuesObject:
        namespaceOverride: unique
        image:
          tag: "1.30.0"
        crds:
          create: true
        config:
          clusterWide: false
          data:
            WATCH_NAMESPACE: unique
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
