apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rustfs-virtual-service
spec:
  gateways:
    - istio-system/ezaf-gateway
  hosts:
    # HPE: rustfs.ingress.pcai0201.fr2.hpecolo.net
    - rustfs.2.28.18.215.sslip.io
  http:
    - match:
        - uri:
            prefix: /rustfs/console/
      route:
        - destination:
            host: rustfs-svc.unique.svc.cluster.local
            port:
              number: 9001
    - route:
        - destination:
            host: rustfs-svc.unique.svc.cluster.local
            port:
              number: 9000
