apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: unique-jwt-auth
  annotations:
    kubernetes.io/ingress.class: kong
plugin: unique-jwt-auth
config:
  uri_param_names:
    - "token"
  allowed_iss:
    # HPE: "https://id.ingress.pcai0201.fr2.hpecolo.net"
    - "https://id.2.28.18.215.sslip.io"
  algorithm: RS256
  # HPE: "https://id.ingress.pcai0201.fr2.hpecolo.net/.well-known/openid-configuration"
  well_known_template: "https://id.2.28.18.215.sslip.io/.well-known/openid-configuration"
  zitadel_project_id: "__ZITADEL_PROJECT_ID__"