apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: unique
spec:
  gatewayClassName: kong
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: http-app
      # HPE: unique.ingress.pcai0201.fr2.hpecolo.net
      hostname: unique.2.28.18.215.sslip.io
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-api
      # HPE: api.ingress.pcai0201.fr2.hpecolo.net
      hostname: api.2.28.18.215.sslip.io
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
