---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-password-secret
  namespace: unique
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCfiKINEaQidM56Pm2Y4qX2vK5WzqAHMidhsL5lELHjGZYIhI8DLox6NHTChwynH3kFsMDRAw3PSJUw2ph8c4KHOzq1KZZgkoT/jKBO9SG/FrEZeufilKZtjEYhtWbT4MOXNwkVcdN6fuEPuNKkRR1EInfdr+1F5eHDl23adcDKG6LpZ+FB5zk4s+9+Ha7TzJRl44D0E6f78yHkEJIAyqlbm3SUJEpMyMD93ZA6w25fvFc/IJbRrwZzwyFzUJ5975fP7HbVUgzCCoWCGsnswISuy/XNSJFhbtJ9O9PlD2QTWqTtDYdakMYrEgsiO2p+7f1Zyep85rH9c6XweYK/YTePK8aoYN89VLTnJHaGpLRb1wgWdoGX51cAh3wjR0S4sbeJqZDqbYM+nfUpi0iPZBX8D+JDSxtd6Qc19ftoC4upY+07cZty2r2zDUy7fE46+0XdfcmteehYWrG39Brdn9dxbb4gdDIH1trSp/F9ijeXtE1C/M2IH9C62hHDgeKtdHyZHsje0+AatIdnizEE5AOeSJUpIsbPaPfZQ4IFU8eSRAE5gSodXEMOwbKxzQyAIjvyRkIryoqZf7ZbSo3ZEfugEwhny4kIQurtQbEZghTv05BdvU3p4ulHtvJBLT3wfh2OkFA60ZW2mBFwbZwUO3sie6xcL7mQyDuZ1IKRd9E5e31C+//EiTgKAIZ2TXNmXs0HHXOJiQaUqHWEfamwSjVHSOQSWFrxBYL/ybfCs1O8SA==
  template:
    metadata:
      name: harbor-password-secret
      namespace: unique
    type: Opaque
