---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-password-secret
  namespace: unique
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgAhczULfWwd4TCyWCwVEhaBvFCdj62cFU9bpqlj2b4ul969fDIaNJwCVBHppatvuEk4tBSmHXhlBda1gDsMAwNZLY32IBiXJ0eHX9q/eaBP9rJUaXgAem+UHcz/ELYZGAEpc3ad6uLgTErxKSH3wQBYBb2vb58wPTJO8Qx0EqJjGJRWNFzTnuCy7v5HnwnPsasGAbcwqA89VXbMInmufBpnyj+gKglFzrJ5pqSgkJPB1Fubks7JS0xjmmow2xyloC8ITnzcbiK+ZFD0/OMPkEoleJSfzZwW2+xqHxmAboxxUWu8Xf64DpGpnu8aZTTSbZGaxqv3ft/P2Qufg+QqI/TJuqXZSjl7YK7/sii4jHBLdzDpKnENlIwDhivv22MPc1mvwuPhr49maI6H0NAcXg4zPA7x8Jm71L6cFBunHCheZ+9FIIonhGwZRAEYpjzqSmTp1sAo1XhzOeIab9EddaDpsTr9Wav2k7SgS8+cA0JpG+d+uDZJpb5UOc/9y6XHjW0wccjHgRLr4UD/plZSsBKXajBcip73EAwphodQYpcGpmNSntqU0w1aieTeDSnz9/WNrJurx/SN/UZIElIk0GCw9Hy2BKb3SqZB5QI3It7XOqSTDZvjda0VuxMdaiZx9RmQBpcnO6GOUvTEKh7oHwMFnrWhBkDi+UykXELSmhxcJMcr0w8lMZmS0EVoI31cJp2/6HHUzv62M1grFidmi+gdYt/sIJk8YimvssOfqa6j/g==
  template:
    metadata:
      name: harbor-password-secret
      namespace: unique
    type: Opaque
