---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-password-secret
  namespace: unique
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCufCt+DejUFT06cTTbkpSaAAOs98uRyIywUiaN+Cg/6cCd4XWPvRUI+Qc+1DI/e6izPoeN1G4dCoKL7I5R0zI56VLqlKimoVkKxcuVCxgHsjNqEBIwvaQj9zYEUMY8SlyBX1FHAdF5d1fhYjn88i9wdXrJpnhH24/0MQAheN/UzIvP42+MzngTo6y0pCadfynfegAgS+pjDirWZbXNaywKbMiriCiO2Je+meG3t5FbWK643NfPQsZwlWxIRAWa/yf+i9PwKGYijBZ9Dth6U0/ZCPmxLEayLeu9r66ZtQYYu3ydwXRnuIFiHDS3z+mSRDiNZN+VHm7Ty+7XpX7mD/pcVNmuYRGKBa4FDLEtteDzdUTqMVSmhwnhw2WuItiy4i0UMNivFvTng4CwiWClP2bVLkaK0RUW1ViVoeDKzzuhs2vPKY7t8EFMkB3NIYTk3TjEQQTDADJHcljV9fzFK5vcihHUXhZmlH+us47joF/f4zhd/3gAhOVOFgG2aKg/XLpa2cKEEF98xRpodYfLC2fxIQUJDRvuQS5vRBJXpwCHu3UntwReiyfKNcYHpAt22BKu1fCnMYvYaugAAK1CL286tja/0ORbxypAik63xwkOWXW4qgMdcHn8nAmcNQu6YTzZpJtdpc3V6p7WnEPm/2LSuBTpeHW9WbHwGjnX9YpaY4d7rjoPn+bmKlx6Y0C6rtbdVNGQ4ocJMP+p6wiKTylDksrIVGHbiaLox9JZMTaz1w==
  template:
    metadata:
      name: harbor-password-secret
      namespace: unique
    type: Opaque
