---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-masterkey-secret
  namespace: unique
spec:
  encryptedData:
    masterkey: AgAeNbOvxyHDgIblm9DBH56wrYM28Tar8CWAbhHCCe4fJxD/A+UoOIEUuOqxVccRbbIp+mvhRD9JYPiUEJ3U1dQZcPjeHiVXoTEe2LtJDmpMQ0FZUlRuaNLy8MNi1fVJkMHv2E9PnG5eppcbefMykiXpaA0VcEd8Qqjcyywwgur5oiXdx7pAnBnurTjvYkK9uSUzGGDQIJ9IK466r4/kLx3ocDoro4nKLOrWHlowbsF30+c1+JGMWiP9ZqMAs0cgV3OAbgwO6vQyDcjOHQam6Skj3t+bamVlIPFJH0LlJeNpCGH+oChCAIFLZm414mA+SrvE63cEn9ieVIz9cGatoOzaz1mzFiuh73gGEB2wlSh4arIsmqpCyz6RmS298sGx8ls2rtg8lJ72hrYgFsb+vzgtWdGTsM1x1rCUgxLn1mT5iC4DXo48sLA84gk8X/mopu6AXEXD/84bJHRxbZg03USbsfRLK2e9TCkgWmTD+dalvzzitZ9b+X0Zws+YBxFDFuE6b1SYyd/nWf1MJrW4LG1qgD7uCgIlfMVQFf7Oy8kJKo/9yPSMSz+AjEBnYKif1P2IrjyGOl7xbfxSLSzp4IjlJO5kMNKWunxez0FqQsoXw5BuSV7VTLKsA8LCSSKNj8Knweqjex1hkdiOy1XuzIBcm9zcwayktnt21pBxPYop4fjgnt/Wjf4pQ6OTu/qU4O8n949vEJGILqbhOzfwid1ItlZLVdVSNV/ZqbGi+AyhgQ==
  template:
    metadata:
      name: zitadel-masterkey-secret
      namespace: unique
    type: Opaque
