---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-masterkey-secret
  namespace: unique
spec:
  encryptedData:
    masterkey: AgAC0/iET5LhVved3YDmMuLJVMLJezI3cYqxS4VhusdQv6iCdDIOjEH4Ima7AR1UdttnQSe+dbDXgwHRYUUM32mrcgs7REhDjJ3eO9FazwD5sePSUHvcMeTea8MFfDQH2qqufL1DBOm0nHMfa7HWNcXBx9bd0A93/TLgIC/OXfSkVbQMZKk+o4jaEy7+uDLciCi8MfO1rcpvTYGUzRFY6MEyuHCjmVZSsHEhtNCDKkZRbgtDoyW0+EpHyUkQm/RdJdpyICxdRHd/8PcNCUK3hQZPHz8OUtWBAfB5AEStnDng2ViHeEk7qDbXGhui1G9Mjd7MnGLGGX2JmTWpAqA5mjM4RkknEDCTGBa5i9byL7hC9GwhaU6wyik19hZSHe76YQ2xCq82YsIBcCkx4UkfaS1X2KqjIbtA9b9XSZS0e2KZXtAG470+iHtlI1btUHEL/QZAAkjlnZo4crYmna+EzlQnhO0OUDXz/Rtd2BWe4UtdaiLflONoBnMJR9cEREvJuInU/jRqjcqVbnOnZKFC2jX+imO4C9PBLv4N3ldyhfFp+WAy92cdJSQihNmfiTZGDSmXUWeJ49ojtAFKK+2GOIIt/faD1istlG2irEVhKMT6IIlAzxpB2FHylBdHc8p3TCTm3u5vrt8EAjl3CDIZjOY0EY8B+cBVfjBJJjPbL+Hdv/9R8UhP/oXIrdWCH6jPvhAq3RQYy+HD1U+cjvo+xW/iNGY5mKf3lWv1cCqIhhPksQ==
  template:
    metadata:
      name: zitadel-masterkey-secret
      namespace: unique
    type: Opaque
