---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-secret-config
  namespace: unique
spec:
  encryptedData:
    config-yaml: AgCMHj6ugc0xuN4gJJxQDAPakjxakvH9Xie97SK59Vm3TKwGnS6b9/NqlPTURfx4xQKviVkIILqIubzSHeaego99Ce2IFj5LGjQnXgOJdoDxxxJhwIZ131Ea6Gsg7VROZ/BaZN5N8ify3ThK4BDDdFlBeUpmr+8M04N950BX1HKso2jOIqpaJU+SOdtdOyPxcG0JYRbKrkSwjDkVZHBFF4aVMPYeszjtBwiy3PLzeDARiWNw3ujae//nT8c+6KbPrCue3JfomkIozeEYb/P6+28FNsNKy1hNCxie+zGaesvIxi9uLwThPJZYk3f8XOTEqkc0rK6vb3DTe1njFdrOOyNPbDyvGF62oL0IaD9qsn5ycbyIDrTn7+wJh2ODc19QVgBxYLj2hCiOJvyaAP6pCOUl2tu5OgNvmjUoslaZOooAtNSytednxa9R9kkTT/XnRzlv1GhahVhspKmMq9yMVDa7DrmKsFVW81Vb787GItR28ZmSu6xZ7fhSMzCNUJUYNvrezIWdIZfkZpRxsYEMtlmNYHWxnpCa4gibEA5MhjvzT/UEbXg4XVtJeAsLbE1R02CVfIfShQJpHuJXndifie3gLnZ6/hUqv+4MxdpfFolcwr5u1EvmQMbDk6zg8RmzGeJRhBwwa8v5qKPsJSguMSA4bEbGB9cGBrnCnyuyRDBzzaaecigvE7qMm3+KxfPvuoYJKGSqmGeffcZJMOhOY428EvY1wUvKD7XTZ0QaPDxyT87PcVWLMI+87PsPdAJtuGET/fPKLtnGLwF/YlwSoHE3hE2NNm88NOxtDf5tZVkNRK24YF93DOT00gI3PcYUvMwCB3in/gImWAAFPhbOD8XJA8K5wnkRdmr6Fm1gspoB4OV32/szLRm7NloFceohL9i3MlP1cTn2+IhPUwsTbwElKPyoqYCFCvfnN56phWepomPEnpFvL0Jg/gNtHH97tA2IpKn/qRszP6AwFIrZo4AYx9k3qQqTKA==
  template:
    metadata:
      name: zitadel-secret-config
      namespace: unique
    type: Opaque
