---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-secret-config
  namespace: unique
spec:
  encryptedData:
    config-yaml: AgBTJuHjLMPGx10pp1gfr+fB36I/poObVP9VCr6YtKjaS9OwoWJ7cNDgVrwij6VqBxA8zQWM6qd/C9S39hp9+t9/Ek6rhReaoim8cuThbQBxJbDY0/vPao1BSHpGyCn5GBGT9fQtCQwxGtJRKqJQAQbfprCLTpVt9l7XN0WoSCBGr8IwHXdCma8A07VNtFO3XW26zodAKt+awePukX6//gFWYlLsncuE6l5ETU2HFk554Ch6H5SZ0qUCHphvQuaO+Sm7Vl0MBVz7U+uxj3QO+v9a4nyQE9gNJx+mq1AtBLsz+jyTfkTfnBwKCR1OQO6LX/oZh9CmKCqWP2YTKGuemr6t3ewDDhznPNtzspCdqvsTRRmOlcb/kXWi2KQSWXHjOgHeP8KG4/ouADmW7ozLBy/NGdTFb2pdA5k+2YQYn6LqA/j0IZWHg0M1pXcJlv/m+9w6/ScpwCshib/ga2xj4AlHG0KGV9he1tEtuhbR2iQhwy22v1JN4oDDbKP2QfXoYXfxsYk0z/ZBq7KfWD+M58aqKnAx7Gu6axYID8gUQjpWvS0Yd8TTkzCWmiZCizDOtxHLdFapGOmpmquyIhK3jLwUG8E69qpR7QIiJLWXEYPPi9jKBCBs7UKqmzbPmP5MCvco665VjgFR0mB4j//Xd7glsGfco5KBMCYznV5Ik4N2yUd9hGskiUc+py7Yr2OMm0TPe9r2BkgSpycLV0sVzNH8bFAr0WD6jxCsG7jmUF0NqdE1CnRpH47RmiDxK86xNufMJUhkU9TujF21U9B9QS9uSt5etfCruha+cgKtj78M4/iTZKwR80tmvYt07rsx/Q8fWsf+ybr/P4pX+eD5F7e4x9MthxUSRg+C+/biC9Y4e5jK4k/+FZM4R1mBtw6VoadtDtomEx3Lrr2t4h6pToRn/VEK7/rWY4VO64zqfW5+bo1QH6iAahub9MD9pre1y1ZKvYwMhte25rm5lTQ1inaMZS+L3+KavQ==
  template:
    metadata:
      name: zitadel-secret-config
      namespace: unique
    type: Opaque
