---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-masterkey-secret
  namespace: unique
spec:
  encryptedData:
    masterkey: AgCMK7RRrM9Z+9kozfKQjtm3qFwBZzsWoSKDrEahw3etMOcO9UhJYDkeWKdcSvXeU3IAwTLpvP3E6ahrukyyJURO0vMIL8Lvla/im8iDX2UlYYYy6quSJR81e8QsLruOgpkHvikyRE5p3hP8bpds5CEvXe85Ti2yFMVyTx9hPMxoFo2BOhW3Ctyd9wznel/iiuob1PTGefgNvsUNOhqsS7S8VlOzxrWljdxGDbAuUpyjdbh43mPxifyrdpc1HboEuk2V1FQtCCsuYezJIBxbhBi7D3TsDv8/ldxukyUX+SrNkneXcpeI4oOQQyEsL/4Mg2g+953wP64jwkiRPVcVHRs5Be31e4rA2867659CcCWKOe0pPFXEyIDilG1ggL1KXQFb9VO7hXoPGXFyV+YPP0Jyvpm7t48/iETQlLuOLKPjKApGkNM8Kjx8wzHBuua/bEUTguZC9xFpYgG3aVmUq3VesbJmg+qZAl3OwndQykeKp1hTQnaAy+yjvaock5M8+Iw7oyKCs1E0oZId+VNftdh5VNW+Fr3fzBUamRgBQkOzewjIfOuag1kvjwwnXqqomc/wqqGw0GJr9ThmvXMioEAq8rSHsZkFe/9GDNo+FWJpqe9lYaiQ/9GtOLZVnK6QKXwNFPTYpAQU9ArlaN8/FtjSVtGFEu0SJ4+l7y0Lo9D+nFHDXNe8Vb3UasmCAGObpDKpKkFfLl1CAG0wVisDGbTuTScs/ZCkPy7xn21upLF3TQ==
  template:
    metadata:
      name: zitadel-masterkey-secret
      namespace: unique
    type: Opaque
