---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-secret-config
  namespace: unique
spec:
  encryptedData:
    config-yaml: AgBjvIXuYIENjgG+LIEuVjqHPj+MMTKjv6Ze2nFXkkMMnboi3RZIEBnlymwAimcxoLMehFLLCwJKIQmtefo0yTidmVLJ57iaA2kcZ3es0u3ctAXwTIX8OFDWAdhAAG/ZabQWnbrfDo8xOXntv0PhBcV42B7JQLGkPgBllgvsDpLhqu7hVeVruz0hih1OYeXUUXCyOGWvdB6+/ZG2cIXnvNHXrseE2IhTDqc4JfzCmkbkkUPWhUh8Qi52k4YWqG6CQ5AxI92XdLjFUaj2tVOqMEPUL9stqRSHHKKX4ma70J3ccf4C5xSgA9qJQhMOFW/QlSzWRUuT0QjstXD1ngDg7wBwn/EaAFyjW2TPT6v+CiXM1VYj/gM6auFqeqXvT9VRhgSi7OluxUTP/LKy/WiUW8AbVNLFfDCmN8bSln+9aRqUIZ9eIZd5DnmGmevF0nakDAxiXWWzQde/fTSWfNsCkvrvETRdoc3cQfB2r+KciC/73oh3TuBtE2Cv5NIidQS/D6n7WpFTQCAPAmv/SGbI/f+83AxddNmstEgTGEUCDMim9bf18Uhq6RL3nT9G0nY8vv9jD+aDq2vbwgDsI9G8QPkhHIVpguQYA5lMGeCEV2xZn+J+iol9Fg/fbjsysDAlzMq3Je+DFsXLljrFU1yWGKUvziuxs9cpWtnd716twfx9+jlnihfZ86Lki5O9oIA5ZXm06Cen92AhUl3RYK206f0N3XsRGhyjQGd6X3QoQwpLa7IMxuMJbibxbfBrflbXIxQzm6wFA2GTDaZu9W1ksmXRi0lB7k2kvtm52u7CvvjTVq6p9xT5lp7x95PdmVSnoxuRrXui6Jhgm9GDo3KcX+XTFIvwX9SYbhdyR3o7DrEdbXtoHFukBf03HpoChWP/gJ3ggSE7g0smOR2BCCEXWu33bCoKJ4zV67qyxYhrTGerc9I1cH655Yg88rdzD0uzYh20d7dSpeu0cG+ZVXEbaXe4DenElnSurR5bJyoYrJgpm/LgEhX3/atX0w3sY+Ffcsifr7gpAGTofHwb+MVbv26Q8aJHUfZwquCk27/CIKAJNto3h+wFmunhLIXuiSImkcqO230KQjfejKpuEAI=
  template:
    metadata:
      name: zitadel-secret-config
      namespace: unique
    type: Opaque
