---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-chat-secrets
  namespace: unique
spec:
  encryptedData:
    CHAT_LXM_ENCRYPTION_KEY: AgBG8rCWHqY0ttTOFQrRiYplVqptnTNt3HVVc+yKV0JQeMKSv2zv23bnfzRwHncN6YFq30POEFA94d9qlyeB+62mcb86OS7exwMojr7hzk3cfrEowTNwTTnrD5gXMjajq35Jy/HWUgpDp3dZCX9jip1gnCzsrAdu9vA6MAQD/r/+F4OV8ypszJ8bIt976kTstfHucEqJu9SfiMahGTXFRoKQCeMnsslCFXmBIaGuQcDpxcRcgP/CHCkdt2Wiu2kxOZXa3OeJ3PW+qoavORb9jiHr/JREZ5PiHn2LBTrOw005HmwWOVDtv67Sc74mk+wcBczN0jdXWhiyV4V4sxZideLuT2m+sLYvCeDVxWerKmy33/XgxWg8dhpUZapx4pPW3ahJ4tzW7nHw27L7uxWp1BHRp+sK8e5fQw2gV9J+70QOo3bZ329vw1rzFg6gqaynACSZ21OediD6OpuzzJMGaxe56WIerEJVnD8LxqywXZzBcbDogUnxMP4I0rQaVgQ4pmLAFl0Z1aiAIHTtRML00k3xfxvpwXWsfcFE6OjZODIz12mJJOZb0klCgIhgUWWJUMA94zD+JrJY9g3o4iCuL5yzry8z8+XOL+4z9nQHcrsQWY3Nce7/8pcyyfEIXZy9PFgw53D4e8tfUXa/CcZhWqAYU2Vbym60lGuHOHMCwH9A6iWoR/ho3RAOfkfDl1duTUA=
  template:
    metadata:
      name: node-chat-secrets
      namespace: unique
    type: Opaque
