---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-chat-secrets
  namespace: unique
spec:
  encryptedData:
    CHAT_LXM_ENCRYPTION_KEY: AgBOw6Ye6nlXrpvi99F/axCmx7FusPIM2PRTbpHNjPQboZQ8fjWKdcdApEls6gk5dAtuyfZhRu78CLNYY34JYhijs5eSjlBe544qhRJPiAUKDap8GQWgynubedMOJm1PVyhdMgUEDoIinHv5eyZYxszkxx7W2Ycyzg7x8c6Tda8rvhWbe6rN2mOY5GjhCqGh0DqAY1AUE/ZBPPIw8KcePtMKcuC00O6VTl27dB/3I+L9/JXCKT06E+jGXWF+qsoEl1Ak0uFE45qrGwtrtvjViznKztGGcsBp/WbWxVtB1q3lJPho2bHbQudmSsFL3KUk7Cbi/Ms9K8q3yiOMxn1uvuX/FWtj9MakpkrVf/Piwmp7aMZcGbdl5GI3Vq83zPwyw8/y9HLpnrw6c0+3qx+cPBLzhhKHtW2wPAudFpp6FVqJ9TwDTifgIPTorHqixHhwyQQAii7OkmBu11VwOtfOtOOxrF3k0xLE8pZjzWJtZZCJFBuSHYmCEJqzxnqmBARQo0aAcgwJSw6H3QfKPBBftj3WDhkPHAPq0xq2OM3XsxkX3EiUxyRiDQYCYVmVnZnw8051Rd79ThNum7xRSULAEOm9/n3dzoqRG7uAPXh3VJuh5xPdvjyetv3lGgSgzJ8IWtpnbkKm55YBiNfmqnK4zThrHVHe0iKgG4ZXeesUd0X0DF8av4L47znRUoEMWAogFLMkqIA/EepaXucTLZRRU+z5XD4q9BikhQLZEvH14vB7yFkSsRYZseDpE0bbERCJwBO6assl6yWXH9EeCsXXLvkP
  template:
    metadata:
      name: node-chat-secrets
      namespace: unique
    type: Opaque
