---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: egress-mitm-ca
  namespace: unique
spec:
  encryptedData:
    tls.crt: AgDVZ8sf8fF37KFchY9wJfyJ+sdu2dBh/kN/TrOBhIzVQ+QZqVvgYWLg9ixpNGNBSNLPX1SthbfynPfaGf4DgKGEBEYDmryip76SJpl5oednImuC377pgN8BlBjze5JAwoqHUWZC+WzN8SIyNzpcw95eRShUfP7yBlnZqZ0IZ5U3PnP3yxnHkN4CyPJgqAI6uL2MIRzVtXvXsuqWTvqQ1tnDdcdD9PMa11coSsxQGc4rjHg4tJlvyODhRh3zwVY9GStaS+JeHaIKvwSCLd3SUjnoaB3yLBIMz82yV9+1t3EgyjhBDrCdMv6s0Q2UCTiLiE5ZqFJMBrykvnDPYoTORNl8HPTxQFKy9uZH4VkWllnun+SYHYU2+VvpFu/uLh6HNtAOSXTes4sYTZdeRrb1lL+qb+H3c96KgSN+RgtUzqm5p8CXwoDqK2w892DTt0GwgFJQ/bnxu0zo4+atVr/Eapa+6oOK8vkhOENkUlmiP/Of9sdeoi2Srv8BVvoKFcpDXFVdTNwidyo8wvJfj27Hih8bG9oF/YHSpbCLtcj27DxSJSq09P6Ndnqxtv+Ekuge0blT+kfanmR6hWT4SiVXeX6803pJlzNVAXK3k7sXwlj0LSRFCrYWd1NwY9pcECGDXsuJOzby77BxzEwxfyXOEmhRoDFw5m1PfDGppcQXpdNJhCJ9VzPpH2/TqWmRGenoNgV6O0Dr6ceX6W4=
    tls.key: AgAOIGm5QY0sFO3fdYr/57kAa0wddvIe5fV2fXT6Cjn2DYd2r7bpSV0XytqvLnM8y7Zko984+JEEEvvBAvYH0/zPoMlLixFRiw0kCjs8Du4Dz90YybkZDekKw8hHZ1pTVQSAIjVM/UcrYBx/icEdNfD7UvYzZKgFFTcDUjxnsF0VEytZy/Hl/pyxqBEn4Vgh0BFIVtKca2yH5lPpMnbyixWnfHdwFMKyj+11b+VLl7whXNkzQ8a87i89PDg/mozYrNomxxhXsC+e0Wc1sWdYFdvyVEZI5tLVS9f7liTACabngScjPH6gKcekWtLToDHZleQL8eEtEACY+49XphHsgVHBqRr5zdJRyl53yozHRytJhfSqgnyFCElPoztSbeifgHjoW/dX68Pm1gM5Q2C911zW/U/5I2dioVIaLDUhb2X3E5Pb0C2VlCRLFGpgWYOdjQAvcStjMRLh9fwC4jR0bnZy+186Ea7WL5AR2liOIXtFfCefl6OPRJoP6pYdsZbfVUsUKct6hJbiQXrDrzan5/5ZvCsJyUKwsRoAF877RVnvbO4fe/ESWWcyWkhtooLDRZi/ua8NR7xbD+VIWARf6+kjxS5Bi+ZNWT8PZgm6A5vbRQneTVjHkoGYGbr55iB0jNJLI4LXSbcWXUtZhmvqudIbqP+IhxBXCNE+UOjgSZP7UJ97P03UQdGTMgOjLXI1wfa8AeRTRoNQN3k=
  template:
    metadata:
      name: egress-mitm-ca
      namespace: unique
    type: kubernetes.io/tls
