---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: egress-mitm-ca
  namespace: unique
spec:
  encryptedData:
    tls.crt: AgB1eBJkzd/QjUmlbo7OtbdVMcZKboLi7kykR7rduw15Wh2QJlFrwgnSiiEdnvCGPpmHL7xAobY8xetHuRvbFaL5MvKhSOgzkCvKkylGZadpC+IV7M58iwUAHsHlTlZNr1bMQdMCNaiVGZF+C2GhnLK7vLjm9IkdcgDNvynHBdOVdaDN1kZMxtWriHe5UGPoXZTJVvJUPMeGFSMUn3V4omD7rVCeDOn7d946ZsVYHIocv7+lNWm9ucThADt8Ois1CkYPDFs5fTvPbyeq15LZndT+BkbVPOaSxNiGvNFl8LF6qXZAo5PQ4ZALPRa8URtk+Bkk+IPBZdG7609vRUNXhXPr2k8BZTfRIRAPslEup47wr0KTtZOqMX5WPMxL6I3sNDdm8+NJjXPQc698EA86TDGuEMwI2SW1uD6aEV8PlJTen+UEJMJdE/aXqeNgnrqMIwl4qz7mVZhbVXOKQihomdn04a7RKVnz5uZZWpmrF23vv6YbDoQd7arbs0w0eD+s2j/hAyZVvS7GR70qCGqEkfV61gL0epWt7EvRJwfCQOZ672Up7CoG7m1XVK+bDgcyUCmIyXu9u5H/hSAac1p8MlitWoSt4ajBx95X3QLZLApZGwl3IaM9qm+ktsVnxJ5mp3I6wdpnT38rGlfJPW5PI5wxApsJBx3H3NdH9Kwu19G7+dk09/AkiH7dE0ayDwVoMSj0VrWgfRsTgbE=
    tls.key: AgAwRRT8viETszIg58hFS/GibJKIA2+GgmceuWU9EWagf4PFgHD+JLbUbcgvlDgmizFaY6Rbpig4lS3ib8zPQA8FEgjlUcbfKLWsxH4Zm1fwyxjzBFIdgruoTZZMwUhjFZTCrYju/Yapt7NG4UkWkTkIwyziRgtd7+d35WuRUUDUP/4C9N2Pt0D+PzXs01A2XsOt1n7WVxZe4hjrynW0Q2k9/s6zuSJmuZLFo4k+3OKzfyTTT9gnr4k1At3v4ZNZdCnRCp1ZOkdJDnwsl0jQ5fNwRHSbU+vca5vb5TMsRd6eJMsT5CHMngI3EWVSvZ9nTtribURvBxRuCdwEykewxWJhK1UBziMX7bKRM8yNwqgRSiRzwXPSHwYtzxg1pePxRk7EU6j0vhriL8+7HLubTFS+npLy0vMW6yCX3fN7aAOVsn6AMfIZ+eVhnYaEZgtOcp9aap+eZcR1RXXauqwoOh3cS7CNtReA4SI5eIC1ddj4Xv39s6RfTulKQeNeG8lyyCXvpFjI5rRbnvP1NH6xOucl/XFnrvFpfeYBETMqChwd73tHkM2dIrlb7sgqQ49fTYfkmpGQLJeAFlLl1J0RgwES3QUFWKXa7FU8oPCZRw1LdCekMnkl4QG1Z5PzjEhgg5ohtDXxK0UIg9ltJ7zbv/xTuqjcZqKahGB9Hlb58OyaHQYMHIs88yOKEWlIfbLvlZeGMt5v4kHmPzw=
  template:
    metadata:
      name: egress-mitm-ca
      namespace: unique
    type: kubernetes.io/tls
