---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: egress-mitm-ca
  namespace: unique
spec:
  encryptedData:
    tls.crt: AgCcYoFKLbkfFrdjr2QNnr1ZVFth9Ju58DSNPIDAFDO2owdw452h+z4NEFwFGk2nPMHhOVwD5ZT8qfkO6TmgDt4YBmfyEzPTRHwVGK70iN0CxQwrbwikw40gjVkTGJCutFfMZJlbzRMipTjzEbUHlHRJnz/8agRQdt286vwW10ntowqMPyQlmtktN/fIatbxLevTh5M1Vyyp0VYkmvXorgyNB5f2E9N++FIugMNhCMLAgYrcxMcSyCKqsOUnaY6/APYSut/JYo4kISmeQQq0KvVRMJCESrtULrq1xc6OA+EAgqJFrQ3KLI/x6MLWmHjUaSaPhsTUoKJw6NusYpLstXr6f2Qo9aqd0y/c+x4gQvwoThfaAgPr5DrtqXVV++uIBKOOx8wzuSdDQlu6Fh1EPfWe3nGIepLRTn8r7fDKuJiFcZ4eBzufpax9lQu72q5d/Ny3zCWd7a/Dj7m7URshui5CfhSGhagOc1aew0m3mkRp63AjBXQu/XMmRMWx6QM5chtSBlkMh+jx8lFCa4HNz9Reuc7QrGgFVo1HwYRs2iLokeyft5a+HHt1BLajH2ekbE73i2N82jTx3Pa48v3whhxaVufjWvoMN97MCInJ+CF+HV9jWS1nFeUfpWrefmVkeFIZFpX4iniwVhpiQ/HEQNUqJuI/5MC+8L9WFMgi63kCPhGZSlkGk9jkk18eAnXjEX7B2BIZdYilq2A=
    tls.key: AgB+ZpsQyDnR0Cpqrw5xQ9nylZb5HywZwxymrIqHcEfgERXl8fMdHGNZgxcWlNshKtSDhpASuJy6yKcE1ZWmHH+z4QWVYALebsaQLwghB8CGbvlIrdwUI2tCi5QBFfAkYP67kU3en2YDfZu4raOJsSwzAWdFKpatsHdMn6iUxTPt03dvqZo2D5tNp6TiQ3sAjgYWeDZs/Y4Awn9y33P7cwXBSXagU3P7YWK/J4HAxkVGlbB3l9G+/XxuflMYqm8vn4Ybvd7nUDOaOOnTNePSuqurC9+nW7EOUZwy1ww6vek5jvuFDCtzNQAqwK0IhPnLvvTwkDLdAOAcS2R9pvIu7D0vHQuPltOgKdYQlvWmQ8AD4ksjgRnQwHuLzX+qH+wgdLuAvR7H37sOG1hEbDi40mal15YhRGjAJ7ROKFsSZqB4Fw3vX/5I48mnNK/frfbg5BmDY7wtVTDqCdaIC6YzdKBtfL9Qx8itQtBlnyDzKVaUwtHm1EssXCpNAJNEcjnXIL8QiQRbyOa1wrUOdyIBkTaqvDQj6LvG0sEpCJfD4xkfR1PQTQ6uDBADIJ/iJleVduhaD/eTzF8vh42dna9wPTPCGdRGWWtOipg8t0j6zTK1LxoTFK9T27EGFd0AwYPrf93lDBhfQ4vhJb0le7rB2zBKinNQX+s01mewZGKauDftTRtJN+s7fegZsqjtN9BsxB5t/qJ9iWrYAUk=
  template:
    metadata:
      name: egress-mitm-ca
      namespace: unique
    type: kubernetes.io/tls
