spec:
  name: node-webhook-scheduler
  rolloutGroup: worker
  autoSync: true
  destination:
    namespace: unique
  source:
    # HPE: oci://harbor.ingress.pcai0201.fr2.hpecolo.net/unique/helm/webhook-scheduler
    repoURL: oci://harbor.localhost/library/helm/webhook-scheduler
    targetRevision: sha256:c6825bbbc628ca3fa922fbf06a9e6f593d4343e59dfb75ac6364b9659028eabc
    path: .
    helm:
      passCredentials: true
      releaseName: node-webhook-scheduler
      valuesObject:
        global:
          image:
            # HPE: harbor.ingress.pcai0201.fr2.hpecolo.net
            registry: harbor.localhost
            pullSecrets:
              - name: harbor-pull-secret
        env:
          UNIQUE_INSTALLATION_ID: hpe-hosted-trial
          # HPE: https://id.ingress.pcai0201.fr2.hpecolo.net
          ZITADEL_ISSUER: http://id.localhost
          ZITADEL_PROJECT_ID: hpe-hosted-trial
        routes:
          gateway:
            name: unique
            namespace: unique
          # HPE: api.ingress.pcai0201.fr2.hpecolo.net
          hostname: api.localhost
        internalServices:
          namespace: unique
        postgresql:
          connection:
            host: postgres-rw.unique.svc.cluster.local
            port: 5432
        redis:
          connection:
            host: redis-master.unique.svc.cluster.local
            port: 6379
        rabbitmq:
          connection:
            host: rabbitmq.unique.svc.cluster.local
            url:
              fromSecret:
                name: node-webhook-scheduler-connections
                key: AMQP_URL
        objectStorage:
          endpoint: http://rustfs-svc.unique.svc.cluster.local:9000
          region: us-east-1
        litellm:
          enabled: true
          connection:
            host: litellm.unique.svc.cluster.local
            port: 4000
        namespaceOverride: unique
