---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-webhook-scheduler-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgB73RIQ4xVl+merote6RFvaISAisr5pDECLgtgh24Geqn8bJgdljce5Fp46HUyEDAPQ1GsYkh9J5CrTmTTbJUBapBeBscbK8eTzxN3zp+B+osjC78d6tEUVIUODDYz8C5b0h8EUGgxojyhxxldahhFWWF8w+2vWRKf5g1I8r/sqtL9vyYpDofJQ9EmwN3ZE+XGp3gAkjzWrPuyZ1n0RqFVK28PE/mCYPy4TgDBzNrCKJc+E8bRNfQ2skGUS+VMs/VwPtVG+ehxVK1clwj/BfoZhqxOirxvy7Fl18dwBJkLmRviXPGRSll5SVAdvJs0p+gs21l1iiglU0OArJLSx33kKqJ5lnd/B0N0GHSLrgnZFu4EAZSgGoDvtsBtMuVNI8Vh+qMbqdHB0BWUjvPXkrkvIr43b9OkZE7Vd+dMHCevBrRDMUOO4uQ+XxgMbn2sLAGdjYPcHt2iVII3o+eGvf+CmXJVRVbe0ky7oFcUj9Z/iJZkHEAdfImRBO0mh2wWMXIfGTyn4Am1E1LKwrLX476yJ4xL6anDvKrBPisbFcnREZqbRX3tbsTd27QbennIU2RWY0RJVblTtuS2h3rIgoxTu+RdcmU9/kqh2OkUsas8rg2UovekrbDrBHYsd0U+z7h3HaWbxT9ikpivVFKkPMVxi3Gx2jIKzHNeEzFG5BF+yeLwAtSS9M+kT2Q71xsaqEjw=
  template:
    metadata:
      name: node-webhook-scheduler-secrets
      namespace: unique
    type: Opaque
