---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-webhook-scheduler-secrets
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgADG3pGOEaecJs3ZuSTyyPGnnmSTkBIIaRbkdBjP/JFI5wGiveZqVZzgK9hTVFaZQaZ3KuXG+5Ri7/kf6oDEMHMBzEpTJoRZQePgDq2DhJ+4Z/dYZG0vdSLSAswauMQNPEUhWdEw8lUHmzzX5nGA+9yHn5X9XnBDUP97o3VGsAgOkk8PgfYYFT5LyL3M2VmgysooT4dc3339y8O1YJ+0gVPT5NhKScHKoddUTyEn+BN5+zvbQBwn3cdexLmi1KlS+tyQzGlIr+emebkgS79BavGZgQSI7s8hzA2oCYBLwVo0maUyaDBVS2YDwstoNUVN5FHaWjQeVjVPYbx+Yf4/J14mTo1uvY2+evB4ezk0K4f1BGgrpQy9LySj3y9jTkTNQpA80ylca52A6h9afWwPL5aWb85EOHo+7U59UNrewoNE7Aldosul8QCE1UDxxKwx1qdc9r1XYkJmjYZxPbW7Fqbf+orLcG2gSRLsz1NNJbd601EK1XIpyC+hqQJy+XUJRlpqIOAWBnycUFoZ84uAxeknc1TYHY4xp+SSajy0+hSVVFoMwy2+DtBSRkG67qqItpKDpwAI1OlsAk/01MO2i05f15KQEXB/C+ldCb9vyeHjzD8YKDIDc0l3TTvD1Izw50Ug8lEC00hNUXtTnJ4JNI7SPYtKGlI5rN7Cqu1vGh/qvDvzntO7B8FXh8RQ213rP4=
  template:
    metadata:
      name: node-webhook-scheduler-secrets
      namespace: unique
    type: Opaque
