spec:
  name: node-app-repository
  rolloutGroup: core
  autoSync: true
  destination:
    namespace: unique
  source:
    # HPE: oci://harbor.ingress.pcai0201.fr2.hpecolo.net/unique/helm/app-repository
    repoURL: oci://harbor.unique.svc.cluster.local/library/helm/app-repository
    targetRevision: sha256:16551dc19bb3b2f5da90d2259d161f28838859773b2cd7f2f92e7ec3a40c5b25
    path: .
    helm:
      passCredentials: true
      releaseName: node-app-repository
      valuesObject:
        global:
          image:
            # HPE: harbor.ingress.pcai0201.fr2.hpecolo.net
            registry: harbor.localhost
            pullSecrets:
              - name: harbor-pull-secret
        env:
          UNIQUE_INSTALLATION_ID: hpe-hosted-trial
          # HPE: https://id.ingress.pcai0201.fr2.hpecolo.net
          ZITADEL_ISSUER: http://id.localhost
          ZITADEL_PROJECT_ID: hpe-hosted-trial
        routes:
          gateway:
            name: unique
            namespace: unique
          # HPE: api.ingress.pcai0201.fr2.hpecolo.net
          hostname: api.localhost
        internalServices:
          namespace: unique
        postgresql:
          connection:
            host: postgres-rw.unique.svc.cluster.local
            port: 5432
            url:
              fromSecret:
                name: node-app-repository-connections
                key: DATABASE_URL
        redis:
          connection:
            host: redis-master.unique.svc.cluster.local
            port: 6379
        rabbitmq:
          connection:
            host: rabbitmq.unique.svc.cluster.local
            url:
              fromSecret:
                name: node-app-repository-connections
                key: AMQP_URL
        objectStorage:
          endpoint: http://rustfs-svc.unique.svc.cluster.local:9000
          region: us-east-1
        litellm:
          enabled: true
          connection:
            host: litellm.unique.svc.cluster.local
            port: 4000
        nameOverride: node-app-repository
        fullnameOverride: node-app-repository
        extraEnvSecrets:
          - node-app-repository-secrets
