---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-app-repository-secrets
  namespace: unique
spec:
  encryptedData:
    ENCRYPTION_KEY: AgBl8Jx346evyj9cbQeHmSOnJfQKA5n2Q0qNMS0B9mLvZyTYZICDwK5CeV0b6ofHMcz6gfZUdQTHBklTZ9ZR9qrIfliKVjt8dRyFzhHXjUk/ik8x0fpOpAK897QK0wyy84H+sNFe7TtOOGlUYKKqKsq4igbA0eFJ6GTj7oIM0W3tWRgO+iCVAC/uyG6OsBEcxTts3ih/krEdn13ZvRMAPGeXhtiLI9E7CYqb+68ZxCf0kDL3T0E37vEByAUQ8JUUqfKxuY42A5Bs1l/eD2pGIN+8NXjrSStQFwSCFid1rg+Apqbuu/wy5c1TIe+ZicjYbV9USEDczkBewMrG+LXNroGgIMap/WC588ixMf0MGMVfwkQGx3TPwKzZqC78Za+uKURqh6uHWrzJAtoBFhWwOq/xnO0wSpqC2vcN/xj7aRrtP8rgkHN0YRSH0wJJ+fNY85qm/D5UMp6SIb6x9r0a+PzFrLealxTjLqR/4rlbInsCoYPpRkJVueHwZv8UUta+7in56nxm1yXTZsM7UtdsMYZA/6P2MuGQekRgj8asKjimwreUA/ZBbpIk/QfQlk0eKvjZwCQRMej64KKl5vP4sfYSfPSRLgHpoNotEmXVfFy5s/etCoxpNIku7rxMdX/up055ZmuV65k2aeUtmvhE9MOZa0M07e7ApqdyjgbKWlW7L4Yieci1yXA5j7pvFRyu5k4OwfNIOvbQR7o3nOCc0WYmVF6jnOQgd54o0m4+qqio9w==
  template:
    metadata:
      name: node-app-repository-secrets
      namespace: unique
    type: Opaque
