---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-app-repository-secrets
  namespace: unique
spec:
  encryptedData:
    ENCRYPTION_KEY: AgBZitgcyrZHosfDgfbT9beswWHuO/BOVb3H3D7hBhOdlR61forQxAfGq4KSy5AO4GxKgWYReBjtJE+CwMt+fIag6vLLDp6HUSFhpOeinRzSCwQE3DpWath5xiCDNdeRHpFxGwQtY6lClt+d6s5iuNlKQ57XqsZ1JKZ/pWT4ZvZdPE4kW4ch3d037CA3KMre63R4Kel7TwICFoVsCRNdUxsIDb6/puyqz9k2lsBJBMHASI/g+6JXxZNKP4goVkHHmDy6iqH6Dzslh/uBYjbFRYHPpnw5ShquUmTfVTNzvKdrEBy9qlQNvyZU4SNYtQTFAVM3+N2bEPACc3uYO0GyLPTVsl9HcaOo/X3sac43XHt3cXNnmMqOmJIRZUMjZJ31XTeaMXhKUDS0dA8y4Dt8HcTN6irsEew2P+5uqCgKagoQXX/iUP/bQkGo8TP0HsCFiEWfsVo34A3D0wfhdX+6u536BlDcAZP5ECBncOuA5jYMOaHIRpJvWtqVoXbjo8jwPuPneDJyS41PK5Tc3uOx+862bBK6JCogkicXiu2Z7N12CnFcvZAcFOguvyrs8jbp0MDvPrdTC4xQMRwlOxAZgUn1k48mB/3ToYdEFcWN8vowgK/i7lSTISIPvRIVVK0bpnUKnyqq52Z/VKZ5aWE1++x1VcTW7IcTJbFtFFrN+1GwErTe8BFYshZCQ9AcIxWSI94YB2qxByXLgPZhFOob1VmDYfT//t1HLUfGAGknWOj+GA==
  template:
    metadata:
      name: node-app-repository-secrets
      namespace: unique
    type: Opaque
