spec:
  name: alloy
  rolloutStep: infrastructure
  autoSync: false
  sources:
    - repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      targetRevision: feat/upgrade-to-2026
      path: "1-system/2-alloy"
      directory:
        recurse: true
        exclude: '{app.yaml}'
    - chart: alloy
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.11.1
      helm:
        releaseName: alloy
        valuesObject:
          alloy:
            mounts:
              varlog: true
            configMap:
              create: false
              name: alloy-config
          serviceMonitor:
            enabled: true
          controller:
            type: daemonset
