apiVersion: v1
kind: ServiceAccount
metadata:
  name: kind-postgres-resource-profile
  namespace: unique
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kind-postgres-resource-profile
  namespace: unique
rules:
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kind-postgres-resource-profile
  namespace: unique
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kind-postgres-resource-profile
subjects:
  - kind: ServiceAccount
    name: kind-postgres-resource-profile
    namespace: unique
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kind-postgres-resource-profile
  namespace: unique
spec:
  backoffLimit: 1000
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kind-postgres-resource-profile
    spec:
      restartPolicy: OnFailure
      serviceAccountName: kind-postgres-resource-profile
      containers:
        - name: kubectl
          image: registry.k8s.io/kubectl:v1.36.1
          command:
            - kubectl
          args:
            - --namespace=unique
            - patch
            - cluster/postgres
            - --type=merge
            - '--patch={"spec":{"resources":{"requests":{"cpu":"1","memory":"4Gi"},"limits":{"cpu":"2","memory":"8Gi"}}}}'
