spec:
  name: agent-sandbox-controller
  rolloutGroup: prerequisites
  autoSync: true
  destination:
    namespace: unique
  syncOptions:
    - ServerSideApply=true
  source:
    # HPE: oci://harbor.ingress.pcai0201.fr2.hpecolo.net/unique/helm/agent-sandbox-controller
    repoURL: oci://harbor.unique.svc.cluster.local/library/helm/agent-sandbox-controller
    path: .
    targetRevision: 0.4.6-rc.1
    helm:
      releaseName: agent-sandbox-controller
      valuesObject:
        router:
          image:
            # HPE: harbor.ingress.pcai0201.fr2.hpecolo.net/unique/images/sandbox-router
            repository: harbor.localhost/library/images/sandbox-router
            tag: v20260514-v0.4.6
            digest: sha256:b8ec35527be94a0f16a91219cf0aec2f35e7cd942db0adfeb2b7cb70a49d666a
          networkPolicy:
            enabled: true
            ingress:
              allowedSources:
                - podSelector:
                    app.kubernetes.io/name: assistants-core
                  namespaceSelector:
                    kubernetes.io/metadata.name: unique
            egress:
              sandboxPort: 8888
              sandboxNamespaceSelector:
                kubernetes.io/metadata.name: unique
