apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-service.fullname" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
data:
  VERSION: {{ .Values.image.tag | quote }}
  PORT: {{ include "backend-service.applicationPort" $ | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
