---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-ingestion-worker-chat
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgAs4e/4k4gygOyDenYvQMBUkFYQhGR/SubirGeD3+BRZ5/IruUhVpP3IIIpFM9ntXmCjJ5Rp9ylGMIebNiBJx7ClNuWAx3kQQIND3lM7pkuOLNpWRvb2uApu7wl685JqwlHbc3auux1J6BiLlA3rnQcrf2DjvQ1VrmgN/l/1B8rKPCkFjV0neDDu+aUMcOSa2SdHHLjGMc90ysFvi9YrwzEbsY+Rbf6TlnR/3YVYaS2/ehSDx/B8ns9GCQhSLJfoHq65LlCCtj3TsmPb5plr0tU5KTHIDuuHEvEOw5Eix7pyKE/9svF+lWJ0OEkDK3eIgDxUae2s8g9FeDqsDhsVxeel3uqAlAjLHwEzJ258tgWdEu3QHli3TIcTU07OjBynDfZrMmSrhcYvgpMY8ryFGdGYQ7aVDm12ChiZtHFls+UlbMQqEc9appsYtAbnFvEftE4KxjzMiKiQ7/fBJFaYQE1xfWUEdagSC4807Q1PeqeEvFXqwj7c0KPp4FuJucivMeSK9IvmiuTvmbwZiREepXd74rd+eerp1ENSGiL/eZAFskiG4OlixCy6Kv+FrkhfhY8ujBPiD7u7UgFUqNLjXg/FWBJljnXqeECNkca5m4N3XfUHoFBpC7/GFoUz9nndE2MMyWqcZvMkA8VTMCMGciIWRpH9WGblwMx79/czUqa5+gHZmnvjBMklqc8050JB3Er+6b6b44SgDo0FMzaKQiPou7oJRS7DowAjjS32j05j6G77nf1j/LV68GS/BxswlpZqB5fcVibGjAuLoEytkNIcIUx
  template:
    metadata:
      creationTimestamp: null
      name: service-ingestion-worker-chat
      namespace: unique
    type: Opaque
