---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-ingestion-worker-chat
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgDXWIewOGRc0wyiI+6pVYfB4RlmNKDRSTAOY0VZnUzQgmdA7fdDp7tNLmSlIMgX8cr27LX8SNk/wlHLCWVGG/luLWPi2LDZE+K4+W5tOtt6t+b0ECjAegxAJ0RGLoILp2OE/Ek73bggXXNbtIo8ujwM7eRf1K+oIpxH1xZ/A/r8kWLKp5eG22e08VFMf4d7tlsnwkdCB4AD9hhfdwIFE4HNee4N21YKO0XcSlx8dOjXrR3ikZVNoRS7dQj4nFAz09AR7p6LxCeD4+cu7e1NxW9kBVo2LByRla/Qzrb8afejuXT9c+HORN5uLqsGWpwRCpm55GrstrYuz2si97r2AJ1BRRUh9XSCrBi+fB/IhA84NPeCv80dM4ISRW/GmhkZKu3ixnd7NK5AE+JZVBXkX2EIJSYEX+6l2aKX26z+HmMWv8Wc6aisd2KFndw8ZXzdFQMGe/v7Vt5j2IsR68m8TZ9fJyMXJ57rxNTvwkrUYdqFPwOriElV39lDZI28AytCFm/oVVSKXRkIZ66ECD+taMKaWjGQLPNrEeUc7DrMPPpGb61KBX5ro3g6pup8/JP3sXkJR2IaOddwkfxhVL3f3gdSHmQV/uNn73/a3dQymJidH6Z5JAjBBn+VOzV13a3pZR5fCGWrtWmkpEYyB3XLnQ8YO0nSk/oZ7dtWJrq2QSLIemRTJGVbTZePGakv2H9cDaP7j/PqWMnw1n/vQe6pMxIt3saLMa79vE0h7Nh6NJ4mzoZDBrlXM1IosVHNEeWaokqf2qdk5n6Cw6UUsCzA4RyW6G1k
  template:
    metadata:
      name: service-ingestion-worker-chat
      namespace: unique
    type: Opaque
