---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-ingestion-worker-chat
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgC6GHvDd7tkfIxV63NZTJxZeUA6KnL/sD0pAoElcuOpI4J+g8APN0HmUVdfz9WutVeEHnIynHu1ZRz1heiBo87FLUmWT9Eoihon7PXQKEjeS90mB2Yaj1VEyhwF/4gsKLKNoSOYgsDvRO5sT0Y5NIEaytVddYEwMtjFoYjZ3gHwZRuPrMeHQU7ruobMQrgsWa8qtJdGBOGdf3NK38LW5BUElIinXI1MBmsp8n0f4kpudoSWt9Cp6JEonTe2c0UwUg4qzvn44Z1N44Y8zKc3Wj8BUQmbwp5LBHcxGcIzf4kVZvgH0y4rXwWhLqqyUSz1lvciDEBlG0lepdiDEp048I2igFVyv2wbG28eiYWOKp0fbCHQvGJZfdfGp6O/zm4Iu83uvGt0zQ97aBCzgQB09Bs6GMg/C1xYoUMo1ba7pCL/m1iTHWKJzW9mSDaFqkuGLLSzdZjrGEmqk2ngS+elh2s7IOUEJcL1TM/VcrDyKcy+3eejWCATulVmmsjqMt9YCvVyiMS15cSJWgloTeTh8aaKksSZvIa9gNXwIvFVC4Vqx2pqWvcBRtUpQHR02e1XapW9tMcSQjOb6c51ICueffLP0e0KvFa2uMnUeXQRF9nSQEbBUsYJC1CTrBoXDBXPw2GvwAgutBeNOTOj0Uuuj5bGEtMWZws6j80eFAW4+4OibjFyrzoNlvPTypRKr3o7nJ3YqK0FoF+FR6veYqB1u9+pDw6HrNMXcUeg+LWPwEQy0M3OHIrig5nfQ2s5nRttuzPtU3cRPPWGjqRALMvFywonMswe
  template:
    metadata:
      name: service-ingestion-worker-chat
      namespace: unique
    type: Opaque
