---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-ingestion-worker-chat
  namespace: unique
spec:
  encryptedData:
    AMQP_URL: AgBAJLcukD7EirawG3y05VWKPW1vy6Ixisnw4mmKbTaZ8IaVM89jknw3OrQrza+TrQnRZtVUELks281gTcUTE5Pms+Nqh56+ChcmJDRnFIHL4kN2m1q6+UjHYkTumabm7FmA6DvYPd7HU3ARSctRYTGoe3OajTOPsrRqFGQVx81I0uBUGYZu+tjVZGxoQY4LLfIuBB2e8wrF+xE5Acd1ys7IqXPWShJgiX9Xcgb1FyRP2FTrd4MzXlrJuMXm4pQGMaIax/m3QM+kJbh1/bGu59F//DfMZyzEo0/scnstKDkEZv+GlrYFVDPJUwzJoreD0XQUaC3UEuyRwxD9SYumZ57xg5spoJ0HgURtJj2I1II+mX00Rt+QNSnELXPNBj28IAFLz5ffsYW8agud11Tm4ee/XKG/S1l1+iowqqzHdQKfLpQvnHnNRpFmd/rHPabgMWYIJbbdD7AkEDzFytXboxprMceIGOpUAm0Vz0cirGt+WVjrRaaFKqgazcM2jUL+qKZKLFkF6QXK2FLkozzuIoClmIb8l0CK9OcIphgiACFuo++F9HRT3pHgTQbHZ3vG4+XbL2AP+G1kbG7cjA+TAwcSHAV4Zu7T3t6mmVhRCRDm1ldlqbFsbGHjICsARJiUe8h4S2TGx0EVA8c5GkwwUtUtmH/T9DtxpjroUSsyqglRqGnPVdEMd73nt50N+/uAHTjMBD3RhW+kfOuQwDWi1Vq1tukNvrh9Pq6EpDc1E6Yj09R89hpIGuz8+crEWHvFiAX8NCGpWVP1fpVOgluV4xJFqVEG
  template:
    metadata:
      name: service-ingestion-worker-chat
      namespace: unique
    type: Opaque
