apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system
  namespace: unique
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: unique.dev/rollout-step
              operator: In
              values:
                - sealed-secrets
        - matchExpressions:
            - key: unique.dev/rollout-step
              operator: In
              values:
                - secrets
          maxUpdate: 0
        - matchExpressions:
            - key: unique.dev/rollout-step
              operator: In
              values:
                - gateway-api
        - matchExpressions:
            - key: unique.dev/rollout-step
              operator: In
              values:
                - operators
        - matchExpressions:
            - key: unique.dev/rollout-step
              operator: In
              values:
                - infrastructure
        - matchExpressions:
            - key: unique.dev/rollout-step
              operator: In
              values:
                - system-services
        - matchExpressions:
            - key: unique.dev/rollout-step
              operator: In
              values:
                - platform-services
  generators:
  - git:
      repoURL: https://github.com/Unique-AG/hpe-hosted-trial
      revision: feat/upgrade-to-2026
      files:
      - path: "1-system/**/app.yaml"
  template:
    metadata:
      name: '{{.spec.name}}'
      namespace: unique
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: unique
  templatePatch: |
    {{- if hasKey .spec "rolloutStep" }}
    metadata:
      labels:
        unique.dev/rollout-step: '{{ .spec.rolloutStep }}'
    {{- end }}
    spec:
      {{- if hasKey .spec "sources" }}
      sources:
        {{- .spec.sources | toYaml | nindent 4 }}
      {{- else }}
      source:
        {{- .spec.source | toYaml | nindent 4 }}
      {{- end }}
      {{- if hasKey .spec "additionalValues" }}
      {{- .spec.additionalValues | toYaml | nindent 2 }}
      {{- end }}
      syncPolicy:
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
        {{- if .spec.autoSync }}
        automated:
          prune: true
          selfHeal: true
        {{- end }}
        syncOptions:
          - CreateNamespace=true
          {{- if hasKey .spec "syncOptions" }}
          {{- .spec.syncOptions | toYaml | nindent 6 }}
          {{- end }}
      {{- if hasKey .spec "ignoreDifferences" }}
      ignoreDifferences:
        {{- .spec.ignoreDifferences | toYaml | nindent 8 }}
      {{- end }}